import type { InsertRecipe, RecipeIngredientRecord, RecipeStepRecord } from "@workspace/db";

const units: Record<string, string> = {
  g: "جم", kg: "كجم", ml: "مل", liter: "لتر", tablespoon: "ملعقة كبيرة", tablespoons: "ملاعق كبيرة",
  teaspoon: "ملعقة صغيرة", teaspoons: "ملاعق صغيرة", medium: "متوسطة", large: "كبيرة", small: "صغيرة",
  cloves: "فصوص", clove: "فص", cup: "كوب", cups: "أكواب", piece: "قطعة", pieces: "قطع", fillets: "فيليه",
};

function recipeIllustration(label: string, background: string, accent: string) {
  const svg = `<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 800 520"><rect width="800" height="520" fill="${background}"/><circle cx="650" cy="90" r="150" fill="${accent}" opacity=".22"/><ellipse cx="400" cy="315" rx="245" ry="70" fill="#f5e6ca" opacity=".95"/><path d="M170 300c24 120 107 164 230 164s206-44 230-164" fill="#fff8ea"/><ellipse cx="400" cy="295" rx="230" ry="73" fill="#8b563c"/><ellipse cx="400" cy="280" rx="210" ry="62" fill="#a66b44"/><g fill="${accent}" opacity=".75"><circle cx="280" cy="275" r="18"/><circle cx="340" cy="300" r="15"/><circle cx="420" cy="267" r="17"/><circle cx="490" cy="300" r="16"/></g><text x="400" y="95" text-anchor="middle" font-family="Arial,sans-serif" font-size="48" font-weight="700" fill="#fff8ea">${label}</text></svg>`;
  return `data:image/svg+xml,${encodeURIComponent(svg)}`;
}

function ingredient(
  ingredientId: string,
  name: string,
  nameArabic: string,
  quantity: number,
  unit: string,
  group: string,
  groupArabic: string,
  notes: string | null = null,
  notesArabic: string | null = null,
  optional = false,
  substitutions: RecipeIngredientRecord["substitutions"] = [],
): RecipeIngredientRecord {
  return {
    ingredientId, name, nameArabic, quantity, unit, unitArabic: units[unit] ?? unit, optional,
    group, groupArabic, notes, notesArabic, substitutions,
  };
}

function substitute(ingredientName: string, ingredientArabic: string, quantity: number, unit: string, effect: string, effectArabic: string) {
  return { ingredient: ingredientName, ingredientArabic, quantity, unit, unitArabic: units[unit] ?? unit, effect, effectArabic };
}

function step(
  stepNumber: number,
  title: string,
  titleArabic: string,
  instruction: string,
  instructionArabic: string,
  durationMinutes: number | null,
  heatLevel: string | null,
  heatLevelArabic: string | null,
  cookingCue: string,
  cookingCueArabic: string,
): RecipeStepRecord {
  return { stepNumber, title, titleArabic, instruction, instructionArabic, durationMinutes, heatLevel, heatLevelArabic, cookingCue, cookingCueArabic };
}

export const egyptianRecipeSeed: InsertRecipe[] = [
  {
    recipeId: "egyptian-ful-medames",
    name: "Egyptian Ful Medames",
    nameArabic: "فول مدمس مصري",
    description: "Slow-warmed fava beans brightened with lemon, cumin, garlic, and olive oil for a generous Egyptian breakfast.",
    descriptionArabic: "فول مدمس دافي ومتبل بالليمون والكمون والثوم وزيت الزيتون لفطار مصري مشبع.",
    cuisine: "Egyptian", category: "Breakfast", dishType: "Breakfast bowl", mainIngredient: "Fava beans",
    cookingTimeMinutes: 20, difficulty: "easy", vegetarian: true, spicy: false, mealType: "Breakfast",
    prepTimeMinutes: 10, cookTimeMinutes: 10, totalTimeMinutes: 20, servings: 4,
    imageUrl: recipeIllustration("FUL", "#315b4b", "#eb6748"),
    tags: ["egyptian", "breakfast", "vegetarian", "budget-friendly"],
    ingredients: [
      ingredient("fava-beans", "Canned fava beans", "فول مدمس معلب", 800, "g", "Main", "الأساسي", "drained but not rinsed", "مصفى من غير شطف"),
      ingredient("garlic", "Garlic", "ثوم", 2, "cloves", "Seasoning", "التتبيلة", "finely grated", "مبشور ناعم"),
      ingredient("lemon", "Lemon juice", "عصير ليمون", 3, "tablespoons", "Seasoning", "التتبيلة"),
      ingredient("cumin", "Ground cumin", "كمون مطحون", 1, "teaspoon", "Seasoning", "التتبيلة"),
      ingredient("olive-oil", "Olive oil", "زيت زيتون", 3, "tablespoons", "Finish", "التقديم"),
      ingredient("tomato", "Tomato", "طماطم", 1, "large", "Garnish", "التزيين", "diced", "مكعبات", true),
      ingredient("green-chili", "Green chili", "فلفل أخضر", 1, "small", "Garnish", "التزيين", "sliced", "شرائح", true, [
        substitute("Chili flakes", "شطة مجروشة", 0.25, "teaspoon", "Adds heat without fresh pepper.", "تدي حرارة من غير فلفل طازة."),
      ]),
      ingredient("salt", "Fine salt", "ملح ناعم", 1, "teaspoon", "Seasoning", "التتبيلة"),
    ],
    steps: [
      step(1, "Warm the beans", "سخّن الفول", "Put the fava beans and 120 ml water in a saucepan. Warm over medium-low for 8 minutes, stirring until creamy but still textured.", "حط الفول مع ١٢٠ مل مية في حلة صغيرة. سخنه على نار متوسطة هادية ٨ دقايق مع التقليب لحد ما يبقى كريمي ولسه فيه قوام.", 8, "Medium-low", "متوسطة هادية", "The beans are hot throughout and a few whole beans remain.", "الفول سخن كله ولسه فيه حبات كاملة."),
      step(2, "Season the bowl", "تبّل الفول", "Mash about one quarter of the beans with a fork. Stir in garlic, lemon juice, cumin, and salt, then taste and adjust the lemon.", "اهرِس حوالي ربع الفول بالشوكة. قلّب الثوم وعصير الليمون والكمون والملح، ودوق واضبط الليمون.", 3, "Off heat", "من غير نار", "The mixture is creamy with a fresh lemon aroma.", "القوام كريمي وريحة الليمون واضحة."),
      step(3, "Finish and serve", "قدّم الفول", "Spoon into warm bowls. Make a well, add olive oil, and finish with tomato and chili if using. Serve with warm baladi bread.", "وزّع الفول في أطباق دافية. اعمل تجويف صغير وحط زيت الزيتون وزيّن بالطماطم والفلفل لو هتستخدمه. قدّمه مع عيش بلدي دافي.", 5, "Off heat", "من غير نار", "Oil sits in a golden pool and the toppings stay bright.", "الزيت عامل لمعة ذهبية والإضافات لسه فريش."),
    ],
  },
  {
    recipeId: "egyptian-taameya",
    name: "Egyptian Taameya (Fava Bean Falafel)",
    nameArabic: "طعمية مصرية",
    description: "Crisp green-centered fava bean falafel made with herbs, onion, garlic, and coriander.",
    descriptionArabic: "طعمية مصرية مقرمشة من بره وخضرا من جوه، معمولة بالفول والخضرة والبصل والثوم والكزبرة.",
    cuisine: "Egyptian", category: "Street food", dishType: "Fritters", mainIngredient: "Fava beans",
    cookingTimeMinutes: 55, difficulty: "medium", vegetarian: true, spicy: false, mealType: "Breakfast",
    prepTimeMinutes: 35, cookTimeMinutes: 20, totalTimeMinutes: 55, servings: 4,
    imageUrl: "https://images.unsplash.com/photo-1593001872095-7d5b3868dd57?auto=format&fit=crop&w=1600&q=85",
    tags: ["egyptian", "street-food", "breakfast", "vegetarian"],
    ingredients: [
      ingredient("dried-fava", "Dried split fava beans", "فول مدشوش ناشف", 300, "g", "Main", "الأساسي", "soaked overnight and drained", "منقوع طول الليل ومصفى"),
      ingredient("onion", "Yellow onion", "بصلة", 1, "medium", "Aromatics", "الخضرة"),
      ingredient("parsley", "Fresh parsley", "بقدونس أخضر", 60, "g", "Herbs", "الخضرة", "stems trimmed", "من غير العيدان"),
      ingredient("cilantro", "Fresh cilantro", "كزبرة خضراء", 40, "g", "Herbs", "الخضرة"),
      ingredient("dill", "Fresh dill", "شبت", 30, "g", "Herbs", "الخضرة"),
      ingredient("garlic", "Garlic", "ثوم", 4, "cloves", "Aromatics", "الخضرة"),
      ingredient("coriander", "Ground coriander", "كزبرة ناشفة", 2, "teaspoons", "Seasoning", "التتبيلة"),
      ingredient("cumin", "Ground cumin", "كمون مطحون", 1, "teaspoon", "Seasoning", "التتبيلة"),
      ingredient("baking-soda", "Baking soda", "بيكربونات الصوديوم", 0.5, "teaspoon", "Seasoning", "التتبيلة"),
      ingredient("sesame", "Sesame seeds", "سمسم", 40, "g", "Coating", "التغطية", "optional coating", "للتغطية الاختيارية", true),
      ingredient("oil", "Neutral frying oil", "زيت للقلي", 750, "ml", "Frying", "القلي"),
      ingredient("salt", "Fine salt", "ملح ناعم", 1.5, "teaspoons", "Seasoning", "التتبيلة"),
    ],
    steps: [
      step(1, "Blend the mixture", "اطحن الخلطة", "Pulse the drained beans, onion, herbs, and garlic in a food processor until fine and evenly green. Scrape down twice; do not turn it into a smooth paste.", "اضرب الفول المصفى والبصل والخضرة والثوم في الكبة لحد ما الخليط يبقى ناعم ولونه أخضر متساوي. اكشط الجوانب مرتين من غير ما تخليه معجون ناعم.", 12, "No heat", "من غير نار", "The mixture holds together when pinched but still has tiny flecks.", "الخلطة بتتماسك لما تضغط عليها ولسه فيها نقط خضرا صغيرة."),
      step(2, "Rest and season", "ريّح وتبّل", "Mix in coriander, cumin, baking soda, and salt. Cover and refrigerate for 30 minutes so the beans hydrate and the falafel holds its shape.", "قلّب الكزبرة الناشفة والكمون وبيكربونات الصوديوم والملح. غطّي الخليط ودخله التلاجة ٣٠ دقيقة عشان يتماسك.", 30, "No heat", "من غير نار", "A small test patty stays intact when lifted.", "قرص اختبار صغير يفضل متماسك لما تشيله."),
      step(3, "Shape the patties", "شكّل الأقراص", "Heat the oil to 175°C. Scoop heaped tablespoons of mixture, flatten slightly, and coat one side with sesame if using.", "سخّن الزيت لحد ١٧٥°م. خد ملاعق كبيرة مليانة من الخليط وشكّلها أقراص صغيرة، وغطي ناحية بالسمسم لو هتستخدمه.", 8, "Medium-high", "متوسطة عالية", "A tiny crumb sizzles immediately without smoking.", "فتفوتة صغيرة تعمل صوت فورًا من غير ما الزيت يدخن."),
      step(4, "Fry until crisp", "اقلي لحد ما تحمر", "Fry in batches for 3–4 minutes per side, turning once, until deep golden and crisp. Drain on a rack and serve hot.", "اقلي على دفعات ٣–٤ دقايق لكل ناحية، واقلب مرة واحدة، لحد ما اللون يبقى دهبي غامق ومقرمش. صفيها على شبكة وقدّمها سخنة.", 12, "Medium-high", "متوسطة عالية", "The outside is crisp and the center is green, cooked, and fluffy.", "الوش مقرمش والداخل أخضر ومستوي وهش."),
    ],
  },
  {
    recipeId: "egyptian-koshari",
    name: "Egyptian Koshari",
    nameArabic: "كشري مصري",
    description: "Egypt's beloved bowl of lentils, rice, macaroni, chickpeas, crispy onions, tomato sauce, and garlic vinegar.",
    descriptionArabic: "طبق مصر المفضل من العدس والأرز والمكرونة والحمص والبصل المحمر وصلصة الطماطم والدقة.",
    cuisine: "Egyptian", category: "Street food", dishType: "Rice and pasta bowl", mainIngredient: "Lentils",
    cookingTimeMinutes: 65, difficulty: "medium", vegetarian: true, spicy: false, mealType: "Lunch",
    prepTimeMinutes: 20, cookTimeMinutes: 45, totalTimeMinutes: 65, servings: 6,
    imageUrl: "https://images.unsplash.com/photo-1601050690597-df0568f70950?auto=format&fit=crop&w=1600&q=85",
    tags: ["egyptian", "street-food", "vegetarian", "budget-friendly"],
    ingredients: [
      ingredient("rice", "Egyptian rice", "أرز مصري", 300, "g", "Rice", "الأرز", "rinsed", "مغسول"),
      ingredient("lentils", "Brown lentils", "عدس بجبة", 250, "g", "Lentils", "العدس", "rinsed", "مغسول"),
      ingredient("macaroni", "Short macaroni", "مكرونة صغيرة", 250, "g", "Pasta", "المكرونة"),
      ingredient("chickpeas", "Cooked chickpeas", "حمص مسلوق", 300, "g", "Topping", "الإضافات"),
      ingredient("onion", "Yellow onions", "بصل", 3, "large", "Crispy onions", "البصل المحمر", "thinly sliced", "شرائح رفيعة"),
      ingredient("flour", "All-purpose flour", "دقيق", 1, "tablespoon", "Crispy onions", "البصل المحمر"),
      ingredient("tomato", "Crushed tomatoes", "طماطم مطحونة", 800, "g", "Tomato sauce", "صلصة الطماطم"),
      ingredient("garlic", "Garlic", "ثوم", 6, "cloves", "Tomato sauce", "صلصة الطماطم", "minced", "مفروم"),
      ingredient("vinegar", "White vinegar", "خل أبيض", 4, "tablespoons", "Dakka", "الدقة"),
      ingredient("oil", "Neutral oil", "زيت", 250, "ml", "Crispy onions", "البصل المحمر"),
      ingredient("cumin", "Ground cumin", "كمون مطحون", 2, "teaspoons", "Seasoning", "التتبيلة"),
      ingredient("chili", "Chili flakes", "شطة", 1, "teaspoon", "Dakka", "الدقة", null, null, true),
      ingredient("salt", "Fine salt", "ملح ناعم", 2, "teaspoons", "Seasoning", "التتبيلة"),
    ],
    steps: [
      step(1, "Cook the lentils", "سوّي العدس", "Cover lentils with 750 ml water and simmer over medium-low for 20 minutes until tender but not splitting. Drain and season with half the salt.", "غطي العدس بـ٧٥٠ مل مية وسيبه على نار متوسطة هادية ٢٠ دقيقة لحد ما يطرى من غير ما يتهرى. صفيه وتبله بنصف الملح.", 20, "Medium-low", "متوسطة هادية", "The lentil skin is tender and the center has a little bite.", "قشرة العدسة طرية والداخل فيه قوام بسيط."),
      step(2, "Cook rice and pasta", "سوّي الأرز والمكرونة", "Cook rice separately with 450 ml water until tender. Boil macaroni in salted water until just tender, then drain and toss with one teaspoon oil.", "سوّي الأرز لوحده مع ٤٥٠ مل مية لحد ما يطرى. اسلق المكرونة في مية بملح لحد ما تستوي، صفيها وقلّبها مع ملعقة صغيرة زيت.", 25, "Medium", "متوسطة", "Rice is fluffy, and pasta is tender without being soft.", "الأرز مفلفل والمكرونة طرية من غير ما تتهرى."),
      step(3, "Make the sauce and dakka", "اعمل الصلصة والدقة", "For the sauce, cook half the garlic in 2 tablespoons oil for 30 seconds, add tomatoes, cumin, and salt, and simmer 15 minutes. Mix remaining garlic, vinegar, 120 ml water, and chili for the dakka.", "للصلصة، شوّح نصف الثوم في ملعقتين زيت ٣٠ ثانية، وضيف الطماطم والكمون والملح وسيبها ١٥ دقيقة. اخلط باقي الثوم والخل و١٢٠ مل مية والشطة للدقة.", 15, "Medium-low", "متوسطة هادية", "The sauce coats a spoon and the vinegar smells sharp but balanced.", "الصلصة تغطي المعلقة وريحة الخل واضحة ومتوازنة."),
      step(4, "Crisp the onions", "حمّر البصل", "Toss onions with flour. Fry in the oil at medium heat in batches until deep golden, 8–10 minutes. Drain well.", "قلّب البصل مع الدقيق. اقليه في الزيت على نار متوسطة على دفعات لحد ما يبقى دهبي غامق، من ٨ لـ١٠ دقايق، وصفيه كويس.", 10, "Medium", "متوسطة", "The onions are crisp and continue darkening slightly after draining.", "البصل مقرمش ولونه بيغمق سنة بعد التصفية."),
      step(5, "Layer and serve", "رصّ وقدّم", "Layer rice, lentils, macaroni, chickpeas, tomato sauce, dakka, and crispy onions. Serve immediately so the toppings stay crisp.", "رص الأرز والعدس والمكرونة والحمص والصلصة والدقة والبصل المحمر. قدّم الطبق فورًا عشان الإضافات تفضل مقرمشة.", 5, "Off heat", "من غير نار", "Each layer stays distinct and the onions remain crisp.", "كل طبقة باينة والبصل لسه مقرمش."),
    ],
  },
  {
    recipeId: "egyptian-molokhia",
    name: "Egyptian Molokhia with Garlic and Coriander",
    nameArabic: "ملوخية مصرية بالثوم والكزبرة",
    description: "Velvety molokhia leaves gently warmed in stock and finished with a sizzling garlic-and-coriander taqliya.",
    descriptionArabic: "ملوخية ناعمة في شوربة خفيفة، متبّلة بتقلية الثوم والكزبرة اللي بتديها ريحتها المصرية المميزة.",
    cuisine: "Egyptian", category: "Vegetables", dishType: "Stew", mainIngredient: "Molokhia leaves",
    cookingTimeMinutes: 30, difficulty: "easy", vegetarian: true, spicy: false, mealType: "Lunch",
    prepTimeMinutes: 10, cookTimeMinutes: 20, totalTimeMinutes: 30, servings: 4,
    imageUrl: "https://images.unsplash.com/photo-1601050690117-94f5f6fa8bd7?auto=format&fit=crop&w=1600&q=85",
    tags: ["egyptian", "vegetarian", "lunch", "sauce"],
    ingredients: [
      ingredient("molokhia", "Frozen chopped molokhia", "ملوخية مفرومة مجمدة", 600, "g", "Main", "الأساسي", "thawed", "مفكوكة"),
      ingredient("stock", "Chicken or vegetable stock", "شوربة فراخ أو خضار", 750, "ml", "Broth", "الشوربة"),
      ingredient("garlic", "Garlic", "ثوم", 8, "cloves", "Taqliya", "التقلية", "finely minced", "مفروم ناعم"),
      ingredient("coriander", "Ground coriander", "كزبرة ناشفة", 2, "teaspoons", "Taqliya", "التقلية"),
      ingredient("butter", "Butter or ghee", "زبدة أو سمنة", 2, "tablespoons", "Taqliya", "التقلية"),
      ingredient("salt", "Fine salt", "ملح ناعم", 1, "teaspoon", "Seasoning", "التتبيلة"),
    ],
    steps: [
      step(1, "Warm the broth", "سخّن الشوربة", "Bring the stock to a gentle simmer in a wide pot. Add salt and keep it hot without a rolling boil.", "سخّن الشوربة لحد غلوة هادية في حلة واسعة. ضيف الملح وخليها سخنة من غير غليان جامد.", 8, "Medium", "متوسطة", "Small bubbles gather around the edge, not across the whole surface.", "فقاقيع صغيرة تظهر على الأطراف مش على السطح كله."),
      step(2, "Add the molokhia", "ضيف الملوخية", "Whisk the molokhia into the hot stock. Warm for 8–10 minutes, stirring often, but never boil or cover the pot.", "انزل بالملوخية في الشوربة السخنة وقلّب بالمضرب. سخنها ٨–١٠ دقايق مع التقليب، من غير غليان ومن غير غطا.", 10, "Low", "هادية", "The leaves are suspended evenly and the surface looks silky, never foamy.", "الملوخية متوزعة والقوام ناعم من غير رغوة."),
      step(3, "Make the taqliya", "اعمل التقلية", "Melt butter in a small pan. Add garlic and coriander and cook 60–90 seconds until fragrant and lightly golden.", "دوب الزبدة في طاسة صغيرة. ضيف الثوم والكزبرة وسيبهم ٦٠–٩٠ ثانية لحد ما الريحة تطلع واللون يبقى دهبي فاتح.", 2, "Medium", "متوسطة", "Garlic smells sweet and is pale gold, not brown.", "ريحة الثوم حلوة ولونه دهبي فاتح مش بني."),
      step(4, "Finish gently", "كمّل بهدوء", "Pour the sizzling taqliya into the molokhia and stir once. Turn off the heat immediately and serve with rice.", "صب التقلية السخنة على الملوخية وقلّب مرة. اقفل النار فورًا وقدّمها مع الأرز.", 2, "Off heat", "من غير نار", "The taqliya blooms across the surface and the molokhia remains pourable.", "التقلية تنتشر على الوش والملوخية تفضل قوامها ناعم وسايب."),
    ],
  },
  {
    recipeId: "egyptian-lentil-soup",
    name: "Egyptian Yellow Lentil Soup",
    nameArabic: "شوربة عدس مصرية",
    description: "A warm yellow lentil soup blended with carrot, potato, cumin, and a bright lemon finish.",
    descriptionArabic: "شوربة عدس أصفر دافية بالخضار والكمون ولمسة ليمون في الآخر.",
    cuisine: "Egyptian", category: "Soup", dishType: "One-pot soup", mainIngredient: "Yellow lentils",
    cookingTimeMinutes: 45, difficulty: "easy", vegetarian: true, spicy: false, mealType: "Lunch",
    prepTimeMinutes: 12, cookTimeMinutes: 33, totalTimeMinutes: 45, servings: 5,
    imageUrl: "https://images.unsplash.com/photo-1547592166-23ac45744acd?auto=format&fit=crop&w=1600&q=85",
    tags: ["egyptian", "soup", "vegetarian", "winter"],
    ingredients: [
      ingredient("yellow-lentils", "Yellow lentils", "عدس أصفر", 300, "g", "Main", "الأساسي", "rinsed", "مغسول"),
      ingredient("onion", "Yellow onion", "بصلة", 1, "large", "Vegetables", "الخضار", "quartered", "أرباع"),
      ingredient("carrot", "Carrot", "جزرة", 1, "large", "Vegetables", "الخضار", "chopped", "مقطعة"),
      ingredient("potato", "Potato", "بطاطساية", 1, "large", "Vegetables", "الخضار", "cubed", "مكعبات"),
      ingredient("tomato", "Tomato", "طماطم", 1, "medium", "Vegetables", "الخضار", "quartered", "أرباع"),
      ingredient("cumin", "Ground cumin", "كمون مطحون", 2, "teaspoons", "Seasoning", "التتبيلة"),
      ingredient("stock", "Vegetable stock or water", "شوربة خضار أو مية", 1.5, "liter", "Liquid", "السائل"),
      ingredient("oil", "Olive oil", "زيت زيتون", 2, "tablespoons", "Finish", "التقديم"),
      ingredient("lemon", "Lemon juice", "عصير ليمون", 2, "tablespoons", "Finish", "التقديم"),
      ingredient("salt", "Fine salt", "ملح ناعم", 2, "teaspoons", "Seasoning", "التتبيلة"),
    ],
    steps: [
      step(1, "Simmer the lentils", "سوّي العدس", "Put lentils, onion, carrot, potato, tomato, stock, cumin, and salt in a pot. Bring to a boil, then reduce to low and simmer 25 minutes.", "حط العدس والبصل والجزر والبطاطس والطماطم والشوربة والكمون والملح في حلة. اغليها، وبعدين وطي النار وسيبها ٢٥ دقيقة.", 25, "Low", "هادية", "The vegetables crush easily and the lentils have collapsed.", "الخضار بتتهرس بسهولة والعدس داب."),
      step(2, "Blend until smooth", "اضرب الشوربة", "Blend with an immersion blender until smooth, or cool slightly and blend in batches. Add water if it is thicker than heavy cream.", "اضرب الشوربة بالخلاط اليدوي لحد ما تنعم، أو هديها شوية واضربها على دفعات. زود مية لو أتقل من قوام الكريمة.", 5, "Off heat", "من غير نار", "The soup flows in a thick ribbon from a spoon.", "الشوربة بتنزل من المعلقة كشريط تقيل."),
      step(3, "Brighten and serve", "ظبط وقدّم", "Return to low heat for 3 minutes. Stir in lemon juice and olive oil, taste for salt, and serve with toasted bread.", "رجّعها على نار هادية ٣ دقايق. قلّب عصير الليمون وزيت الزيتون، دوق الملح وقدّمها مع عيش محمص.", 3, "Low", "هادية", "Lemon lifts the flavor without making the soup sour.", "الليمون مدي انتعاش من غير طعم حامض زيادة."),
    ],
  },
  {
    recipeId: "egyptian-hawawshi",
    name: "Egyptian Hawawshi",
    nameArabic: "حواوشي مصري",
    description: "Seasoned minced beef pressed into baladi bread and baked until the bread is crisp and the filling is juicy.",
    descriptionArabic: "لحمة مفرومة متبلة جوه العيش البلدي، تتخبز لحد ما العيش يقرمش واللحمة تفضل طرية.",
    cuisine: "Egyptian", category: "Beef", dishType: "Stuffed flatbread", mainIngredient: "Beef",
    cookingTimeMinutes: 45, difficulty: "medium", vegetarian: false, spicy: true, mealType: "Dinner",
    prepTimeMinutes: 20, cookTimeMinutes: 25, totalTimeMinutes: 45, servings: 4,
    imageUrl: "https://images.unsplash.com/photo-1565299507177-b0ac66763828?auto=format&fit=crop&w=1600&q=85",
    tags: ["egyptian", "street-food", "beef", "dinner"],
    ingredients: [
      ingredient("beef", "Ground beef", "لحمة مفرومة", 500, "g", "Filling", "الحشوة", "15% fat", "نسبة دهون ١٥٪"),
      ingredient("onion", "Yellow onion", "بصلة", 1, "large", "Filling", "الحشوة", "very finely chopped", "مفرومة ناعم جدًا"),
      ingredient("pepper", "Green bell pepper", "فلفل أخضر", 1, "medium", "Filling", "الحشوة", "finely chopped", "مفروم ناعم"),
      ingredient("tomato", "Tomato", "طماطم", 1, "medium", "Filling", "الحشوة", "seeded and chopped", "منزوعة البذر ومفرومة"),
      ingredient("cumin", "Ground cumin", "كمون مطحون", 1, "teaspoon", "Seasoning", "التتبيلة"),
      ingredient("paprika", "Paprika", "بابريكا", 1, "teaspoon", "Seasoning", "التتبيلة"),
      ingredient("chili", "Chili flakes", "شطة", 0.5, "teaspoon", "Seasoning", "التتبيلة", null, null, true),
      ingredient("bread", "Baladi bread", "عيش بلدي", 4, "pieces", "Bread", "العيش"),
      ingredient("oil", "Neutral oil", "زيت", 2, "tablespoons", "Bread", "العيش"),
      ingredient("salt", "Fine salt", "ملح ناعم", 1.5, "teaspoons", "Seasoning", "التتبيلة"),
    ],
    steps: [
      step(1, "Mix the filling", "اخلط الحشوة", "Combine beef, onion, pepper, tomato, cumin, paprika, chili, and salt. Mix with your hands for 2 minutes until sticky and evenly seasoned.", "اخلط اللحمة والبصل والفلفل والطماطم والكمون والبابريكا والشطة والملح بإيدك دقيقتين لحد ما الحشوة تتماسك وتتبل كويس.", 5, "No heat", "من غير نار", "The mixture clings together and no dry seasoning remains.", "الخلطة ماسكة في بعضها ومفيش توابل ناشفة باينة."),
      step(2, "Fill the bread", "احشي العيش", "Open each bread pocket carefully and spread one quarter of the filling in a thin, even layer. Brush both sides with oil.", "افتح كل رغيف بالراحة وافرد ربع الحشوة طبقة رفيعة ومتساوية. ادهن الناحيتين بالزيت.", 12, "No heat", "من غير نار", "The filling reaches the edges without making the bread bulge.", "الحشوة واصلة للأطراف من غير ما العيش ينتفخ."),
      step(3, "Bake until crisp", "اخبز لحد ما يقرمش", "Heat the oven to 220°C. Bake on a rack or hot tray for 10–12 minutes per side, turning once, until the beef reaches 71°C and the bread is crisp.", "سخّن الفرن على ٢٢٠°م. اخبز على شبكة أو صينية سخنة ١٠–١٢ دقيقة لكل ناحية، واقلب مرة، لحد ما اللحمة توصل ٧١°م والعيش يقرمش.", 25, "High", "عالية", "The bread is crisp at the edges and the center is fully cooked.", "العيش مقرمش من الأطراف واللحمة مستوية من جوه."),
      step(4, "Rest and slice", "ريّح وقطّع", "Rest for 5 minutes, then cut into wedges and serve with tahini, pickles, or a simple salad.", "ريّحه ٥ دقايق، وبعدين قطعه مثلثات وقدّمه مع طحينة أو مخلل أو سلطة بسيطة.", 5, "Off heat", "من غير نار", "The juices settle instead of running out when sliced.", "العصارة بتهدى ومبتنزلش كلها وقت التقطيع."),
    ],
  },
  {
    recipeId: "egyptian-sayadeya-fish",
    name: "Egyptian Sayadeya Fish with Spiced Rice",
    nameArabic: "سمك صيادية بالأرز",
    description: "Pan-seared white fish with caramelized onions, cumin, and richly seasoned Egyptian rice.",
    descriptionArabic: "سمك أبيض متحمّر مع بصل مكرمل وكمون، جنب أرز صيادية متبل بطعم غني.",
    cuisine: "Egyptian", category: "Seafood", dishType: "Fish and rice", mainIngredient: "White fish",
    cookingTimeMinutes: 50, difficulty: "medium", vegetarian: false, spicy: false, mealType: "Dinner",
    prepTimeMinutes: 15, cookTimeMinutes: 35, totalTimeMinutes: 50, servings: 4,
    imageUrl: "https://images.unsplash.com/photo-1534482421-64566f976cfa?auto=format&fit=crop&w=1600&q=85",
    tags: ["egyptian", "seafood", "rice", "dinner"],
    ingredients: [
      ingredient("fish", "White fish fillets", "فيليه سمك أبيض", 700, "g", "Fish", "السمك", "boneless", "من غير شوك"),
      ingredient("rice", "Egyptian short-grain rice", "أرز مصري", 300, "g", "Rice", "الأرز", "rinsed", "مغسول"),
      ingredient("onion", "Yellow onions", "بصل", 3, "large", "Rice", "الأرز", "thinly sliced", "شرائح رفيعة"),
      ingredient("garlic", "Garlic", "ثوم", 3, "cloves", "Seasoning", "التتبيلة", "minced", "مفروم"),
      ingredient("cumin", "Ground cumin", "كمون مطحون", 2, "teaspoons", "Seasoning", "التتبيلة"),
      ingredient("coriander", "Ground coriander", "كزبرة ناشفة", 1, "teaspoon", "Seasoning", "التتبيلة"),
      ingredient("stock", "Fish or vegetable stock", "شوربة سمك أو خضار", 600, "ml", "Rice", "الأرز"),
      ingredient("flour", "All-purpose flour", "دقيق", 3, "tablespoons", "Fish", "السمك"),
      ingredient("oil", "Neutral oil", "زيت", 5, "tablespoons", "Cooking", "الطبخ"),
      ingredient("lemon", "Lemon juice", "عصير ليمون", 2, "tablespoons", "Fish", "السمك"),
      ingredient("salt", "Fine salt", "ملح ناعم", 2, "teaspoons", "Seasoning", "التتبيلة"),
    ],
    steps: [
      step(1, "Season the fish", "تبّل السمك", "Pat the fillets dry. Season with lemon juice, 1 teaspoon cumin, half the coriander, and half the salt. Dust lightly with flour.", "نشّف الفيليه كويس. تبله بعصير الليمون ونصف الكمون ونصف الكزبرة ونصف الملح. غطيه بطبقة خفيفة دقيق.", 10, "No heat", "من غير نار", "The fish is evenly coated and dry enough to sear.", "السمك متغطي بالتساوي وسطحه ناشف كفاية للتحمير."),
      step(2, "Caramelize the onions", "كرمل البصل", "Heat 2 tablespoons oil over medium-low. Cook onions for 15 minutes, stirring often, until deep golden. Add garlic for the final minute and transfer half to a plate.", "سخّن ملعقتين زيت على نار متوسطة هادية. سوّي البصل ١٥ دقيقة مع التقليب لحد ما يبقى دهبي غامق. ضيف الثوم آخر دقيقة واطلع نصف الخليط في طبق.", 16, "Medium-low", "متوسطة هادية", "The onions are soft, deep golden, and sweet-smelling.", "البصل طري ولونه دهبي غامق وريحته حلوة."),
      step(3, "Cook the rice", "سوّي الأرز", "Add rice, remaining spices, and stock to the pot. Bring to a boil, cover, reduce to low, and cook 18 minutes. Rest covered for 5 minutes.", "ضيف الأرز وباقي التوابل والشوربة للحلة. اغليها، غطيها، وطي النار وسيبها ١٨ دقيقة. ريّح الأرز ٥ دقايق وهو متغطّي.", 23, "Low", "هادية", "The grains are tender, separate, and the stock is absorbed.", "الحبات طرية ومفلفلة والشوربة اتشربت."),
      step(4, "Sear and plate", "حمّر وقدّم", "Sear fish in the remaining oil over medium-high for 3–4 minutes per side, until opaque and flaky. Serve over rice with the reserved onions.", "حمّر السمك في باقي الزيت على نار متوسطة عالية ٣–٤ دقايق لكل ناحية لحد ما يبقى أبيض ويتفتت بسهولة. قدّمه فوق الأرز مع البصل المحفوظ.", 8, "Medium-high", "متوسطة عالية", "The center reaches 63°C and flakes with gentle pressure.", "الداخل يوصل ٦٣°م ويتفتت بضغط خفيف."),
    ],
  },
  {
    recipeId: "egyptian-roast-chicken",
    name: "Egyptian Spiced Roast Chicken",
    nameArabic: "فراخ مصرية متبلة في الفرن",
    description: "Tender chicken roasted with onion, lemon, garlic, cumin, coriander, and warm Egyptian spices.",
    descriptionArabic: "فراخ طرية في الفرن بالبصل والليمون والثوم والكمون والكزبرة وتوابل مصرية دافية.",
    cuisine: "Egyptian", category: "Chicken", dishType: "Roast", mainIngredient: "Chicken",
    cookingTimeMinutes: 75, difficulty: "easy", vegetarian: false, spicy: false, mealType: "Dinner",
    prepTimeMinutes: 15, cookTimeMinutes: 60, totalTimeMinutes: 75, servings: 4,
    imageUrl: "https://images.unsplash.com/photo-1532550907401-a500c9a57435?auto=format&fit=crop&w=1600&q=85",
    tags: ["egyptian", "chicken", "family-friendly", "dinner"],
    ingredients: [
      ingredient("chicken", "Chicken thighs", "وراك فراخ", 1, "kg", "Main", "الأساسي", "bone-in, skin-on", "بالعظم والجلد"),
      ingredient("onion", "Yellow onion", "بصلة", 2, "medium", "Aromatics", "الخضرة", "quartered", "أرباع"),
      ingredient("lemon", "Lemon juice", "عصير ليمون", 3, "tablespoons", "Marinade", "التتبيلة"),
      ingredient("garlic", "Garlic", "ثوم", 5, "cloves", "Marinade", "التتبيلة", "crushed", "مهروس"),
      ingredient("cumin", "Ground cumin", "كمون مطحون", 2, "teaspoons", "Spices", "التوابل"),
      ingredient("coriander", "Ground coriander", "كزبرة ناشفة", 2, "teaspoons", "Spices", "التوابل"),
      ingredient("paprika", "Paprika", "بابريكا", 1, "teaspoon", "Spices", "التوابل"),
      ingredient("oil", "Olive oil", "زيت زيتون", 3, "tablespoons", "Marinade", "التتبيلة"),
      ingredient("salt", "Fine salt", "ملح ناعم", 2, "teaspoons", "Spices", "التوابل"),
    ],
    steps: [
      step(1, "Marinate the chicken", "تبّل الفراخ", "Mix lemon, garlic, cumin, coriander, paprika, oil, and salt. Coat the chicken and rest for 30 minutes at room temperature or up to overnight in the refrigerator.", "اخلط الليمون والثوم والكمون والكزبرة والبابريكا والزيت والملح. غطي الفراخ وسيبها ٣٠ دقيقة في درجة حرارة الغرفة أو ليلة في التلاجة.", 30, "No heat", "من غير نار", "The spice paste coats every piece and smells bright.", "خلطة التوابل مغلفة كل قطعة وريحتهـا منعشة."),
      step(2, "Start the roast", "ابدأ التسوية", "Heat the oven to 220°C. Arrange onions in a roasting dish, place chicken skin-side up, and roast for 20 minutes.", "سخّن الفرن على ٢٢٠°م. رص البصل في صينية وحط الفراخ والجلد لفوق، واخبز ٢٠ دقيقة.", 20, "High", "عالية", "The skin starts to bronze and the onions soften around the chicken.", "الجلد يبدأ يحمر والبصل يطرى حوالين الفراخ."),
      step(3, "Finish gently", "كمّل بهدوء", "Reduce the oven to 190°C and roast 35–40 minutes more, basting once, until the thickest thigh reaches 74°C.", "وطي الفرن لـ١٩٠°م وكمل ٣٥–٤٠ دقيقة، وادهن الفراخ بالعصارة مرة، لحد ما أسمك جزء يوصل ٧٤°م.", 40, "Medium", "متوسطة", "The juices run clear and the skin is crisp at the edges.", "العصارة تنزل شفافة والجلد مقرمش من الأطراف."),
      step(4, "Rest and serve", "ريّح وقدّم", "Rest the chicken for 10 minutes before serving with the roasted onions and pan juices.", "ريّح الفراخ ١٠ دقايق قبل التقديم مع البصل المحمر والعصارة اللي في الصينية.", 10, "Off heat", "من غير نار", "The juices settle and the meat stays moist when sliced.", "العصارة تهدى واللحمة تفضل طرية وقت التقطيع."),
    ],
  },
  {
    recipeId: "egyptian-mahshi",
    name: "Egyptian Stuffed Vegetables (Mahshi)",
    nameArabic: "محشي خضار مصري",
    description: "Tender zucchini and peppers filled with herby tomato rice and gently simmered until the grains are fluffy.",
    descriptionArabic: "كوسة وفلفل محشيين أرز بالطماطم والخضرة، بيتسووا بهدوء لحد ما الأرز يستوي والخضار يطرى.",
    cuisine: "Egyptian", category: "Vegetables", dishType: "Stuffed vegetables", mainIngredient: "Zucchini",
    cookingTimeMinutes: 75, difficulty: "medium", vegetarian: true, spicy: false, mealType: "Lunch",
    prepTimeMinutes: 25, cookTimeMinutes: 50, totalTimeMinutes: 75, servings: 5,
    imageUrl: "https://images.unsplash.com/photo-1547592180-85f173990554?auto=format&fit=crop&w=1600&q=85",
    tags: ["egyptian", "vegetarian", "vegetables", "lunch"],
    ingredients: [
      ingredient("zucchini", "Small zucchini", "كوسة صغيرة", 8, "pieces", "Vegetables", "الخضار", "cored, keeping the base", "مفرغة مع ترك القاعدة"),
      ingredient("pepper", "Green bell peppers", "فلفل أخضر", 4, "pieces", "Vegetables", "الخضار", "seeded", "منزوع البذر"),
      ingredient("rice", "Egyptian rice", "أرز مصري", 300, "g", "Filling", "الحشوة", "rinsed", "مغسول"),
      ingredient("tomato", "Grated tomatoes", "طماطم مبشورة", 500, "g", "Filling", "الحشوة"),
      ingredient("onion", "Yellow onion", "بصلة", 1, "medium", "Filling", "الحشوة", "finely chopped", "مفرومة ناعم"),
      ingredient("parsley", "Fresh parsley", "بقدونس", 40, "g", "Filling", "الحشوة", "chopped", "مفروم"),
      ingredient("dill", "Fresh dill", "شبت", 30, "g", "Filling", "الحشوة", "chopped", "مفروم"),
      ingredient("coriander", "Fresh cilantro", "كزبرة خضراء", 30, "g", "Filling", "الحشوة", "chopped", "مفرومة"),
      ingredient("stock", "Vegetable stock", "شوربة خضار", 700, "ml", "Cooking liquid", "سائل التسوية"),
      ingredient("oil", "Olive oil", "زيت زيتون", 3, "tablespoons", "Filling", "الحشوة"),
      ingredient("salt", "Fine salt", "ملح ناعم", 2, "teaspoons", "Seasoning", "التتبيلة"),
    ],
    steps: [
      step(1, "Make the filling", "حضّر الحشوة", "Mix rice, tomatoes, onion, herbs, oil, and salt. Leave the mixture raw; the rice will swell inside the vegetables.", "اخلط الأرز والطماطم والبصل والخضرة والزيت والملح. سيب الخلطة نية؛ الأرز هيكبر جوه الخضار.", 10, "No heat", "من غير نار", "The rice is evenly coated and the mixture is loose, not dry.", "الأرز متغطي بالطماطم والخلطة سايبة مش ناشفة."),
      step(2, "Fill the vegetables", "احشي الخضار", "Fill each zucchini and pepper only two-thirds full, leaving room for the rice to expand. Stand them tightly in a pot.", "احشي كل كوسة وفلفلة لحد الثلثين بس عشان الأرز يكبر. رص الخضار جنب بعض بإحكام في حلة.", 15, "No heat", "من غير نار", "There is visible space at the top of every piece.", "في مساحة واضحة فوق كل واحدة."),
      step(3, "Simmer", "سوّي المحشي", "Pour stock around the vegetables until it reaches halfway up their sides. Bring to a boil, cover, reduce to low, and simmer 40 minutes.", "صب الشوربة حوالين الخضار لحد نص ارتفاعه. اغليها، غطي الحلة، وطي النار وسيبها ٤٠ دقيقة.", 40, "Low", "هادية", "The rice is tender and the vegetables can be pierced easily.", "الأرز طري والخضار يدخل فيه الشوكة بسهولة."),
      step(4, "Rest and serve", "ريّح وقدّم", "Turn off the heat and rest covered for 10 minutes. Lift out carefully and serve with the cooking broth.", "اقفل النار وسيب المحشي متغطّي ١٠ دقايق. طلعه بالراحة وقدمه مع الشوربة.", 10, "Off heat", "من غير نار", "The filling is set but still moist, and the vegetables hold their shape.", "الحشوة ماسكة ولسه طرية والخضار محافظ على شكله."),
    ],
  },
  {
    recipeId: "egyptian-basbousa",
    name: "Egyptian Basbousa",
    nameArabic: "بسبوسة مصرية",
    description: "Golden semolina cake soaked with lemon-scented syrup and finished with almonds for a tender crumb.",
    descriptionArabic: "بسبوسة سميد ذهبية متشربة شربات بالليمون ومزيّنة باللوز، طرية من جوه.",
    cuisine: "Egyptian", category: "Dessert", dishType: "Semolina cake", mainIngredient: "Semolina",
    cookingTimeMinutes: 50, difficulty: "easy", vegetarian: true, spicy: false, mealType: "Dessert",
    prepTimeMinutes: 15, cookTimeMinutes: 35, totalTimeMinutes: 50, servings: 12,
    imageUrl: "https://images.unsplash.com/photo-1571877227200-a0d98ea607e9?auto=format&fit=crop&w=1600&q=85",
    tags: ["egyptian", "dessert", "baking", "snack"],
    ingredients: [
      ingredient("semolina", "Fine semolina", "سميد ناعم", 300, "g", "Batter", "الخليط"),
      ingredient("sugar", "Granulated sugar", "سكر", 100, "g", "Batter", "الخليط"),
      ingredient("coconut", "Desiccated coconut", "جوز هند", 50, "g", "Batter", "الخليط", null, null, true),
      ingredient("butter", "Melted butter", "زبدة سايحة", 120, "g", "Batter", "الخليط"),
      ingredient("yogurt", "Plain yogurt", "زبادي", 180, "g", "Batter", "الخليط"),
      ingredient("almonds", "Almonds", "لوز", 12, "pieces", "Garnish", "التزيين", "halved", "أنصاف"),
      ingredient("sugar-syrup", "Sugar for syrup", "سكر للشربات", 250, "g", "Syrup", "الشربات"),
      ingredient("water", "Water for syrup", "مية للشربات", 180, "ml", "Syrup", "الشربات"),
      ingredient("lemon", "Lemon juice", "عصير ليمون", 1, "tablespoon", "Syrup", "الشربات"),
      ingredient("vanilla", "Vanilla", "فانيليا", 1, "teaspoon", "Syrup", "الشربات"),
    ],
    steps: [
      step(1, "Make the syrup", "اعمل الشربات", "Boil sugar and water for 5 minutes. Add lemon juice and vanilla, boil 1 minute more, then cool completely.", "اغلي السكر والمية ٥ دقايق. ضيف الليمون والفانيليا واغلي دقيقة كمان، وبعدين سيبه يبرد خالص.", 8, "Medium", "متوسطة", "The syrup lightly coats a spoon and is cool before the cake is baked.", "الشربات بيغطي المعلقة بطبقة خفيفة وبارد قبل ما الكيكة تستوي."),
      step(2, "Mix the batter", "اخلط البسبوسة", "Heat the oven to 180°C. Mix semolina, sugar, coconut, melted butter, and yogurt just until combined; do not knead.", "سخّن الفرن على ١٨٠°م. اخلط السميد والسكر وجوز الهند والزبدة والزبادي لحد ما يتجمعوا بس؛ متعجنش.", 7, "No heat", "من غير نار", "The batter is moist and crumbly, not elastic.", "الخليط رطب ومفتت مش مطاطي."),
      step(3, "Bake and score", "اخبز وقطّع", "Press into a greased 24 cm pan. Score 12 pieces and place an almond on each. Bake 30–35 minutes until deep golden.", "افرد الخليط في صينية ٢٤ سم مدهونة. علّم ١٢ قطعة وحط لوزة على كل واحدة. اخبز ٣٠–٣٥ دقيقة لحد ما اللون يبقى دهبي غامق.", 35, "Medium", "متوسطة", "The edges are deeply golden and the center feels set when tapped.", "الأطراف دهبية غامقة والوسط ثابت لما تخبط عليه."),
      step(4, "Soak and rest", "اسقي وسيبها ترتاح", "Pour the cold syrup over the hot basbousa immediately. Rest at least 30 minutes before cutting along the score marks.", "صب الشربات البارد على البسبوسة السخنة فورًا. سيبها ٣٠ دقيقة على الأقل قبل التقطيع على العلامات.", 30, "Off heat", "من غير نار", "All syrup is absorbed and the surface looks glossy, not wet.", "الشربات اتشرب كله والوش لامع من غير ما يبقى مبلول."),
    ],
  },
];