import type { InsertRecipe, RecipeIngredientRecord, RecipeStepRecord } from "@workspace/db";

const arabicUnits: Record<string, string> = {
  g: "جم", kg: "كجم", ml: "مل", liter: "لتر", cup: "كوب", cups: "أكواب", tablespoon: "ملعقة كبيرة",
  tablespoons: "ملاعق كبيرة", teaspoon: "ملعقة صغيرة", teaspoons: "ملاعق صغيرة", medium: "متوسطة",
  large: "كبيرة", small: "صغيرة", cloves: "فصوص", clove: "فص", pieces: "قطع", piece: "قطعة",
  fillets: "فيليه", cans: "علب", slices: "شرائح", sticks: "أعواد",
};

function illustration(label: string, background: string, accent: string) {
  const svg = `<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 800 520"><rect width="800" height="520" fill="${background}"/><circle cx="650" cy="90" r="150" fill="${accent}" opacity=".22"/><ellipse cx="400" cy="315" rx="245" ry="70" fill="#f5e6ca"/><path d="M170 300c24 120 107 164 230 164s206-44 230-164" fill="#fff8ea"/><ellipse cx="400" cy="295" rx="230" ry="73" fill="#8b563c"/><ellipse cx="400" cy="280" rx="210" ry="62" fill="#a66b44"/><g fill="${accent}" opacity=".75"><circle cx="280" cy="275" r="18"/><circle cx="340" cy="300" r="15"/><circle cx="420" cy="267" r="17"/><circle cx="490" cy="300" r="16"/></g><text x="400" y="95" text-anchor="middle" font-family="Arial,sans-serif" font-size="44" font-weight="700" fill="#fff8ea">${label}</text></svg>`;
  return `data:image/svg+xml,${encodeURIComponent(svg)}`;
}

type IngredientInput = Omit<RecipeIngredientRecord, "unitArabic" | "substitutions"> & {
  substitutions?: RecipeIngredientRecord["substitutions"];
};
type StepInput = RecipeStepRecord;
type RecipeInput = Omit<InsertRecipe, "imageUrl" | "ingredients" | "steps"> & {
  imageLabel: string;
  imageBackground: string;
  imageAccent: string;
  ingredients: IngredientInput[];
  steps: StepInput[];
};

function recipe(input: RecipeInput): InsertRecipe {
  return {
    ...input,
    imageUrl: illustration(input.imageLabel, input.imageBackground, input.imageAccent),
    ingredients: input.ingredients.map((item) => ({
      ...item,
      unitArabic: arabicUnits[item.unit] ?? item.unit,
      substitutions: item.substitutions ?? recipeSubstitutions[input.recipeId]?.[item.ingredientId] ?? [],
    })),
  };
}

const noSwap = (ingredient: string, ingredientArabic: string) => [{
  ingredient,
  ingredientArabic,
  quantity: 0,
  unit: "none",
  unitArabic: "لا يوجد",
  effect: "No suitable substitution is recommended because it changes the dish's defining texture or flavor.",
  effectArabic: "لا يُنصح ببديل مناسب لأن تغييره يبدل القوام أو الطعم الأساسي للطبق.",
}];

const substitution = (ingredient: string, ingredientArabic: string, quantity: number, unit: string, effect: string, effectArabic: string): RecipeIngredientRecord["substitutions"] => [{
  ingredient, ingredientArabic, quantity, unit, unitArabic: arabicUnits[unit] ?? unit, effect, effectArabic,
}];

const recipeSubstitutions: Record<string, Record<string, RecipeIngredientRecord["substitutions"]>> = {
  "egyptian-bamia-stew": { okra: substitution("Fresh okra", "بامية طازة", 600, "g", "Use frozen okra thawed and dried; it will be softer but works in the same stew.", "استخدم بامية مجمدة مفكوكة وناشفة؛ هتكون أطرى لكنها مناسبة لنفس التسبيكة.") },
  "egyptian-kofta-tahini": { beef: substitution("Ground beef", "لحمة مفرومة", 600, "g", "Ground lamb gives a richer kofta; keep the same quantity and reduce added oil if very fatty.", "اللحمة الضاني المفرومة تدي كفتة أغنى؛ استخدم نفس الكمية وقلل الزيت لو دهنية جدًا.") },
  "egyptian-shrimp-rice": { shrimp: substitution("Raw shrimp", "جمبري ني", 500, "g", "Use firm white fish cut into 3 cm pieces and cook until opaque and flaky.", "استخدم سمك أبيض متماسك مقطع ٣ سم وسوّيه لحد ما يبقى معتم ويتفتت.") },
  "egyptian-macarona-beshamel": { mozzarella: substitution("Mozzarella", "موتزاريلا", 100, "g", "Use grated mild cheddar for the optional topping; it browns more deeply.", "استخدم شيدر خفيف مبشور بنفس الكمية للوش الاختياري؛ هيتحمر أكتر.") },
  "egyptian-roz-bel-laban": { milk: substitution("Whole milk", "لبن كامل الدسم", 1, "liter", "Use evaporated milk diluted with 500 ml water for a similarly creamy pudding.", "استخدم لبن مبخر مخفف بـ٥٠٠ مل مية لنفس القوام الكريمي تقريبًا.") },
  "egyptian-baked-eggplant": { eggplant: substitution("Eggplants", "باذنجان", 3, "medium", "Use zucchini cut lengthwise; roast until tender and shorten the roasting time by about 5 minutes.", "استخدم كوسة متقسمة بالطول؛ اشويها لحد ما تطرى وقلل وقت الشوي حوالي ٥ دقايق.") },
  "lebanese-hummus": { chickpeas: substitution("Cooked chickpeas", "حمص مسلوق", 500, "g", "Use well-cooked white beans for a milder dip; blend them fully before adjusting water.", "استخدم فاصوليا بيضا مستوية كويس لتغميسة أهدى؛ اضربها تمامًا قبل ضبط المية.") },
  "indian-butter-chicken": { chicken: substitution("Boneless chicken thighs", "وراك فراخ مخلية", 700, "g", "Boneless chicken breast works at the same weight; simmer 2 minutes less and check for 74°C.", "صدور الفراخ المخلية مناسبة بنفس الوزن؛ قلل التسوية دقيقتين وتأكد من وصولها لـ٧٤°م.") },
  "japanese-chicken-teriyaki": { chicken: substitution("Bone-in chicken thighs", "وراك فراخ بالعظم", 900, "g", "Use boneless thighs at 700 g and reduce the covered cooking time by about 4 minutes.", "استخدم ٧٠٠ جم وراك مخلية وقلل وقت التسوية المغطاة حوالي ٤ دقايق.") },
  "mexican-chicken-tacos": { chicken: substitution("Boneless chicken thighs", "وراك فراخ مخلية", 600, "g", "Use boneless chicken breast at the same weight; slice thinly and stop at 74°C.", "استخدم صدور فراخ مخلية بنفس الوزن؛ قطعها رفيعًا وأوقف التسوية عند ٧٤°م.") },
  "korean-beef-bulgogi": { beef: substitution("Beef sirloin", "شرائح ستيك لحمة", 600, "g", "Use thinly sliced boneless chicken thigh and cook until it reaches 74°C.", "استخدم وراك فراخ مخلية شرائح رفيعة وسوّيها لحد ما توصل ٧٤°م.") },
  "egyptian-fattah": { beef: substitution("Beef chuck", "لحمة كندوز", 900, "g", "Use boneless lamb shoulder at the same weight and simmer until fork-tender.", "استخدم كتف ضاني مخلية بنفس الوزن وسيبها تتسوى لحد ما الشوكة تدخل بسهولة.") },
  "italian-eggplant-parmigiana": { mozzarella: substitution("Mozzarella", "موتزاريلا", 250, "g", "Use low-moisture provolone at the same weight so the casserole does not become watery.", "استخدم بروفولون قليل الرطوبة بنفس الوزن عشان الصينية ما تطلعش مية.") },
  "thai-green-curry": { tofu: substitution("Firm tofu", "توفو متماسك", 300, "g", "Use cooked chickpeas at the same weight and add them during the final 5 minutes.", "استخدم حمص مسلوق بنفس الوزن وضيفه في آخر ٥ دقايق.") },
  "egyptian-kebda-eskandarani": { liver: substitution("Beef liver", "كبدة بقري", 600, "g", "Use thinly sliced chicken liver at the same weight and cook until fully opaque.", "استخدم كبدة فراخ شرائح رفيعة بنفس الوزن وسوّيها لحد ما تبقى معتمة بالكامل.") },
  "egyptian-chicken-orzo-soup": { orzo: substitution("Orzo pasta", "لسان عصفور", 150, "g", "Use small soup pasta at the same weight and check it after 8 minutes because it may cook faster.", "استخدم مكرونة شوربة صغيرة بنفس الوزن وافحصها بعد ٨ دقايق لأنها ممكن تستوي أسرع.") },
  "egyptian-carrot-orange-salad": { orange: substitution("Oranges", "برتقال", 2, "large", "Use two tangerines; their segments are smaller, so fold them in gently at the end.", "استخدم ٢ يوسفي؛ فصوصه أصغر فقلّبها بالراحة في الآخر.") },
};
const ingredient = (ingredientId: string, name: string, nameArabic: string, quantity: number, unit: string, group: string, groupArabic: string, notes: string | null = null, notesArabic: string | null = null, optional = false, substitutions?: RecipeIngredientRecord["substitutions"]): IngredientInput => ({
  ingredientId, name, nameArabic, quantity, unit, group, groupArabic, notes, notesArabic, optional, substitutions,
});

const step = (stepNumber: number, title: string, titleArabic: string, instruction: string, instructionArabic: string, durationMinutes: number | null, heatLevel: string | null, heatLevelArabic: string | null, cookingCue: string, cookingCueArabic: string): StepInput => ({
  stepNumber, title, titleArabic, instruction, instructionArabic, durationMinutes, heatLevel, heatLevelArabic, cookingCue, cookingCueArabic,
});

export const recipeExpansionSeed: InsertRecipe[] = [
  recipe({
    recipeId: "egyptian-bamia-stew", name: "Egyptian Okra and Tomato Stew", nameArabic: "بامية مصرية بالصلصة", description: "Tender okra simmered in garlicky tomato sauce with coriander and a bright splash of vinegar.", descriptionArabic: "بامية طرية في صلصة طماطم بالثوم والكزبرة ولمسة خل تديها طعمها المصري.", cuisine: "Egyptian", category: "Vegetables", dishType: "Stew", mainIngredient: "Okra", cookingTimeMinutes: 50, difficulty: "medium", vegetarian: true, spicy: false, mealType: "Lunch", prepTimeMinutes: 15, cookTimeMinutes: 35, totalTimeMinutes: 50, servings: 4, tags: ["egyptian", "vegetarian", "vegetables", "lunch"], imageLabel: "BAMIA", imageBackground: "#4d6b46", imageAccent: "#e2a23b",
    ingredients: [
      ingredient("okra", "Fresh okra", "بامية طازة", 600, "g", "Main", "الأساسي", "washed and dried", "مغسولة وناشفة"), ingredient("tomatoes", "Crushed tomatoes", "طماطم مطحونة", 600, "g", "Sauce", "الصلصة"), ingredient("onion", "Yellow onion", "بصلة", 1, "large", "Sauce", "الصلصة", "finely diced", "مفرومة ناعم"), ingredient("garlic", "Garlic", "ثوم", 6, "cloves", "Seasoning", "التتبيلة", "minced", "مفروم"), ingredient("coriander", "Ground coriander", "كزبرة ناشفة", 2, "teaspoons", "Seasoning", "التتبيلة"), ingredient("vinegar", "White vinegar", "خل أبيض", 2, "tablespoons", "Finish", "اللمسة الأخيرة"), ingredient("water", "Water", "مية", 120, "ml", "Cooking liquid", "سائل التسوية"), ingredient("oil", "Olive oil", "زيت زيتون", 3, "tablespoons", "Cooking", "الطبخ"), ingredient("salt", "Fine salt", "ملح ناعم", 1.5, "teaspoons", "Seasoning", "التتبيلة"), ingredient("chili", "Chili flakes", "شطة", 0.5, "teaspoon", "Seasoning", "التتبيلة", null, null, true),
    ],
    steps: [
      step(1, "Prepare the okra", "جهّز البامية", "Trim only the stem caps without cutting into the pods. Toss with vinegar and leave for 10 minutes, then rinse quickly and dry thoroughly.", "شيل غطا البامية من غير ما تفتح الحبات. قلبها مع الخل ١٠ دقايق، وبعدها اشطفها بسرعة ونشفها كويس.", 10, "No heat", "من غير نار", "The pods are dry and intact, so they will not become slimy in the pot.", "الحبات ناشفة ومتماسكة عشان ما تطلعش لزوجة في الحلة."),
      step(2, "Build the sauce", "حضّر الصلصة", "Warm oil over medium heat. Cook onion with half the salt for 6 minutes, add garlic and coriander for 45 seconds, then pour in tomatoes and simmer uncovered for 12 minutes.", "سخّن الزيت على نار متوسطة. سوّي البصل مع نصف الملح ٦ دقايق، وضيف الثوم والكزبرة ٤٥ ثانية، ثم ضيف الطماطم وسيبها من غير غطا ١٢ دقيقة.", 19, "Medium", "متوسطة", "The sauce darkens slightly and a spoon leaves a clear track for a moment.", "الصلصة لونها يغمق شوية والمعلقة تسيب خط واضح لحظة."),
      step(3, "Simmer the okra", "سوّي البامية", "Add okra and 120 ml water. Bring to a gentle bubble, cover, and cook on low for 15 minutes, stirring once halfway through.", "ضيف البامية و١٢٠ مل مية. وصلها لغلوة هادية، غطيها، وسيبها على نار هادية ١٥ دقيقة مع تقليبة في النص.", 15, "Low", "هادية", "A fork enters the pods easily while they still hold their shape.", "الشوكة تدخل بسهولة والحبات لسه محافظة على شكلها."),
      step(4, "Finish and serve", "كمّل وقدّم", "Uncover and simmer 3 minutes to thicken. Stir in remaining salt and chili if using, then serve hot with rice.", "افتح الغطا وسيبها ٣ دقايق تتقل. ضيف باقي الملح والشطة لو هتستخدمها وقدّمها سخنة مع الأرز.", 3, "Low", "هادية", "The sauce clings to the okra and smells sweet rather than sharp.", "الصلصة ماسكة في البامية وريحتهـا حلوة من غير حدة."),
    ],
  }),
  recipe({
    recipeId: "egyptian-kofta-tahini", name: "Egyptian Kofta with Tahini", nameArabic: "كفتة مصرية بالطحينة", description: "Juicy cumin-scented beef kofta baked over onions and served with lemony tahini.", descriptionArabic: "كفتة لحمة طرية بالكمون تتخبز فوق البصل وتتقدم مع طحينة بالليمون.", cuisine: "Egyptian", category: "Meat", dishType: "Baked kofta", mainIngredient: "Beef", cookingTimeMinutes: 45, difficulty: "medium", vegetarian: false, spicy: false, mealType: "Dinner", prepTimeMinutes: 20, cookTimeMinutes: 25, totalTimeMinutes: 45, servings: 4, tags: ["egyptian", "beef", "dinner", "high-protein"], imageLabel: "KOFTA", imageBackground: "#75453d", imageAccent: "#d8a64c",
    ingredients: [
      ingredient("beef", "Ground beef", "لحمة مفرومة", 600, "g", "Kofta", "الكفتة", "20% fat", "بنسبة دهون ٢٠٪"), ingredient("onion", "Yellow onion", "بصل", 1, "large", "Kofta", "الكفتة", "grated and squeezed", "مبشور ومتصفي"), ingredient("parsley", "Fresh parsley", "بقدونس", 40, "g", "Kofta", "الكفتة", "chopped", "مفروم"), ingredient("cumin", "Ground cumin", "كمون مطحون", 2, "teaspoons", "Seasoning", "التتبيلة"), ingredient("allspice", "Ground allspice", "بهارات مشكلة", 1, "teaspoon", "Seasoning", "التتبيلة"), ingredient("salt", "Fine salt", "ملح ناعم", 1.5, "teaspoons", "Seasoning", "التتبيلة"), ingredient("tahini", "Tahini", "طحينة", 120, "g", "Sauce", "الصوص"), ingredient("lemon", "Lemon juice", "عصير ليمون", 3, "tablespoons", "Sauce", "الصوص"), ingredient("water", "Water", "مية", 100, "ml", "Sauce", "الصوص"), ingredient("oil", "Olive oil", "زيت زيتون", 1, "tablespoon", "Cooking", "الطبخ"),
    ],
    steps: [
      step(1, "Mix and rest", "اخلط وريّح", "Combine beef, squeezed onion, parsley, cumin, allspice, and salt. Knead for 2 minutes until sticky, cover, and chill for 15 minutes.", "اخلط اللحمة والبصل المتصفي والبقدونس والكمون والبهارات والملح. اعجن دقيقتين لحد ما تمسك، غطيها ودخلها التلاجة ١٥ دقيقة.", 17, "No heat", "من غير نار", "The mixture holds a ridge when pressed and feels cold and cohesive.", "الخلطة ماسكة أثر الضغط وباردة ومتماسكة."),
      step(2, "Shape and roast", "شكّل واخبز", "Heat oven to 220°C. Shape eight oval kofta pieces, brush with oil, and bake on a hot tray for 10 minutes.", "سخّن الفرن على ٢٢٠°م. شكّل ٨ قطع كفتة بيضاوية، ادهنها بالزيت واخبزها على صينية سخنة ١٠ دقايق.", 10, "High", "عالية", "The outside is browned but the center is not yet fully done.", "السطح اتحمر لكن الوسط لسه بيكمل تسوية."),
      step(3, "Make the tahini", "حضّر الطحينة", "Whisk tahini, lemon juice, water, and a pinch of salt. Add water one tablespoon at a time until smooth and pourable.", "اضرب الطحينة مع الليمون والمية ورشة ملح. زود المية ملعقة كبيرة كل مرة لحد ما تبقى ناعمة وسايبة.", 5, "No heat", "من غير نار", "The sauce turns pale and thickens before loosening into a ribbon.", "الصوص لونه يفتح ويتقل الأول وبعدين ينزل كشريط ناعم."),
      step(4, "Finish safely", "كمّل التسوية", "Pour tahini around the kofta and bake 10–12 minutes more. The thickest piece must reach 71°C; rest 5 minutes before serving.", "صب الطحينة حوالين الكفتة واخبز ١٠–١٢ دقيقة كمان. أسمك قطعة لازم توصل ٧١°م، وريّحها ٥ دقايق قبل التقديم.", 12, "Medium-high", "متوسطة عالية", "The kofta is firm, juicy, and fully opaque in the center.", "الكفتة متماسكة وعصارتها موجودة والداخل مستوي بالكامل."),
    ],
  }),
  recipe({
    recipeId: "egyptian-shrimp-rice", name: "Egyptian Spiced Shrimp Rice", nameArabic: "أرز بالجمبري على الطريقة المصرية", description: "Garlic shrimp folded through cumin-scented rice with peppers, tomato, and fresh lemon.", descriptionArabic: "جمبري بالثوم متقلب مع أرز بالكمون والفلفل والطماطم ولمسة ليمون فريش.", cuisine: "Egyptian", category: "Seafood", dishType: "Rice skillet", mainIngredient: "Shrimp", cookingTimeMinutes: 40, difficulty: "medium", vegetarian: false, spicy: false, mealType: "Dinner", prepTimeMinutes: 15, cookTimeMinutes: 25, totalTimeMinutes: 40, servings: 4, tags: ["egyptian", "seafood", "rice", "quick"], imageLabel: "SHRIMP", imageBackground: "#466879", imageAccent: "#ed7e55",
    ingredients: [
      ingredient("shrimp", "Raw shrimp", "جمبري ني", 500, "g", "Main", "الأساسي", "peeled and deveined", "متقشر ومنزوع العرق"), ingredient("rice", "Egyptian rice", "أرز مصري", 300, "g", "Rice", "الأرز", "rinsed", "مغسول"), ingredient("pepper", "Green bell pepper", "فلفل أخضر", 1, "large", "Vegetables", "الخضار", "diced", "مكعبات"), ingredient("tomato", "Tomato", "طماطم", 2, "medium", "Vegetables", "الخضار", "diced", "مكعبات"), ingredient("onion", "Yellow onion", "بصلة", 1, "medium", "Vegetables", "الخضار", "diced", "مكعبات"), ingredient("garlic", "Garlic", "ثوم", 5, "cloves", "Seasoning", "التتبيلة", "minced", "مفروم"), ingredient("cumin", "Ground cumin", "كمون مطحون", 1, "teaspoon", "Seasoning", "التتبيلة"), ingredient("stock", "Vegetable or fish stock", "شوربة خضار أو سمك", 600, "ml", "Rice", "الأرز"), ingredient("oil", "Neutral oil", "زيت نباتي", 3, "tablespoons", "Cooking", "الطبخ"), ingredient("lemon", "Lemon juice", "عصير ليمون", 2, "tablespoons", "Finish", "التقديم"), ingredient("salt", "Fine salt", "ملح ناعم", 1.5, "teaspoons", "Seasoning", "التتبيلة"),
    ],
    steps: [
      step(1, "Season the shrimp", "تبّل الجمبري", "Toss shrimp with half the garlic, lemon juice, half the salt, and cumin. Refrigerate while the rice starts.", "قلّب الجمبري مع نصف الثوم وعصير الليمون ونصف الملح والكمون. دخله التلاجة لحد ما تبدأ الأرز.", 10, "No heat", "من غير نار", "Every shrimp is glossy and lightly coated, with no pooling liquid.", "كل حبة جمبري لامعة ومتغطية من غير سائل كتير."),
      step(2, "Start the rice", "ابدأ الأرز", "Cook onion and pepper in 1 tablespoon oil over medium for 6 minutes. Add tomato and rice, stir 2 minutes, then add stock and bring to a boil.", "سوّي البصل والفلفل في ملعقة زيت على نار متوسطة ٦ دقايق. ضيف الطماطم والأرز وقلّب دقيقتين، ثم ضيف الشوربة واغليها.", 10, "Medium-high", "متوسطة عالية", "The rice is coated and the stock bubbles across the surface.", "الأرز متغلف والشوربة بتغلي على السطح كله."),
      step(3, "Steam the rice", "سوّي الأرز", "Cover, reduce to low, and cook 16 minutes. Turn off heat and leave covered for 5 minutes before fluffing.", "غطي الحلة وطي النار وسيب الأرز ١٦ دقيقة. اقفل النار وسيبه متغطّي ٥ دقايق قبل ما تفلفله.", 21, "Low", "هادية", "The grains are tender and no stock remains beneath them.", "حبات الأرز طرية ومفيش شوربة باقية تحتها."),
      step(4, "Cook and fold in shrimp", "سوّي وقلّب الجمبري", "Sear shrimp in the remaining oil over medium-high for 2 minutes per side, until pink and opaque. Fold through the rice and serve immediately.", "حمّر الجمبري في باقي الزيت على نار متوسطة عالية دقيقتين لكل ناحية لحد ما يبقى وردي ومعتم. قلبه في الأرز وقدّم فورًا.", 5, "Medium-high", "متوسطة عالية", "The shrimp curl into a loose C and reach 63°C without becoming rubbery.", "الجمبري يتكور كحرف C واسع ويوصل ٦٣°م من غير ما ينشف."),
    ],
  }),
  recipe({
    recipeId: "egyptian-macarona-beshamel", name: "Egyptian Macarona Bechamel", nameArabic: "مكرونة بشاميل مصرية", description: "Baked pasta layered with seasoned beef and a smooth nutmeg-scented white sauce until bubbling and golden.", descriptionArabic: "مكرونة بالبشاميل واللحمة المفرومة، متحمرة من فوق وطبقاتها طرية ومتتبلة.", cuisine: "Egyptian", category: "Pasta", dishType: "Baked pasta", mainIngredient: "Pasta", cookingTimeMinutes: 75, difficulty: "medium", vegetarian: false, spicy: false, mealType: "Dinner", prepTimeMinutes: 25, cookTimeMinutes: 50, totalTimeMinutes: 75, servings: 6, tags: ["egyptian", "pasta", "beef", "comfort-food"], imageLabel: "BECHAMEL", imageBackground: "#6b4c43", imageAccent: "#d6a56d",
    ingredients: [
      ingredient("pasta", "Penne pasta", "مكرونة قلم", 500, "g", "Pasta", "المكرونة"), ingredient("beef", "Ground beef", "لحمة مفرومة", 500, "g", "Filling", "الحشوة"), ingredient("onion", "Yellow onion", "بصلة", 1, "medium", "Filling", "الحشوة", "diced", "مكعبات"), ingredient("tomato", "Crushed tomatoes", "طماطم مطحونة", 250, "g", "Filling", "الحشوة"), ingredient("flour", "All-purpose flour", "دقيق", 70, "g", "Bechamel", "البشاميل"), ingredient("milk", "Whole milk", "لبن كامل الدسم", 750, "ml", "Bechamel", "البشاميل"), ingredient("butter", "Butter", "زبدة", 70, "g", "Bechamel", "البشاميل"), ingredient("nutmeg", "Ground nutmeg", "جوزة الطيب", 0.25, "teaspoon", "Bechamel", "البشاميل"), ingredient("cheese", "Mozzarella", "موتزاريلا", 100, "g", "Topping", "الوش", null, null, true), ingredient("salt", "Fine salt", "ملح ناعم", 2, "teaspoons", "Seasoning", "التتبيلة"), ingredient("pepper", "Black pepper", "فلفل أسود", 1, "teaspoon", "Seasoning", "التتبيلة"),
    ],
    steps: [
      step(1, "Cook the pasta and beef", "سوّي المكرونة واللحمة", "Boil pasta in salted water for 2 minutes less than the package time and drain. Cook onion in a pan for 5 minutes, add beef, salt, pepper, and tomato, and simmer 12 minutes.", "اسلق المكرونة في مية بملح دقيقتين أقل من وقت العبوة وصفيها. سوّي البصل ٥ دقايق، ضيف اللحمة والملح والفلفل والطماطم وسيبها ١٢ دقيقة.", 20, "Medium", "متوسطة", "Pasta is firm in the center and the beef is fully browned with no pink spots.", "المكرونة ماسكة من النص واللحمة اتحمرت كلها من غير أجزاء وردية."),
      step(2, "Make the sauce", "اعمل البشاميل", "Melt butter over medium-low. Whisk in flour for 90 seconds, then add milk gradually while whisking. Simmer 7 minutes with nutmeg until it coats a spoon.", "دوب الزبدة على نار متوسطة هادية. ضيف الدقيق واضرب ٩٠ ثانية، ثم ضيف اللبن تدريجيًا مع التقليب. سيبه ٧ دقايق مع جوزة الطيب لحد ما يغطي المعلقة.", 10, "Medium-low", "متوسطة هادية", "The sauce is smooth and thick enough to leave a line when a finger crosses the spoon.", "الصوص ناعم وتقيل لدرجة إن الإصبع يسيب خط على المعلقة."),
      step(3, "Layer the dish", "رصّ الصينية", "Heat oven to 190°C. Mix one third of the bechamel through the pasta. Layer half pasta, all beef, remaining pasta, then spread the rest of the sauce and optional cheese on top.", "سخّن الفرن على ١٩٠°م. قلّب ثلث البشاميل مع المكرونة. رص نصف المكرونة وكل اللحمة وباقي المكرونة، وافرد باقي الصوص والجبنة الاختيارية.", 10, "No heat", "من غير نار", "The sauce reaches every edge and the top is level so it browns evenly.", "الصوص واصل لكل الأطراف والوش متساوي عشان يتحمر بالتساوي."),
      step(4, "Bake and rest", "اخبز وريّح", "Bake 30 minutes until bubbling at the edges, then broil 3–5 minutes until golden. Rest 15 minutes before cutting so the layers set.", "اخبز ٣٠ دقيقة لحد ما تغلي من الأطراف، وبعدين حمّر الوش ٣–٥ دقايق. ريّحها ١٥ دقيقة قبل التقطيع عشان الطبقات تمسك.", 45, "Medium-high", "متوسطة عالية", "The center is hot and bubbling, the top is golden, and slices stand without flooding.", "الوسط سخن وبيغلي والوش دهبي والقطعة تمسك من غير ما الصوص يسيل."),
    ],
  }),
  recipe({
    recipeId: "egyptian-roz-bel-laban", name: "Egyptian Rice Pudding", nameArabic: "أرز باللبن مصري", description: "Creamy rice pudding scented with vanilla and mastic, chilled until softly set and finished with nuts.", descriptionArabic: "أرز باللبن كريمي بالفانيليا والمستكة، بيتقدم ساقع ومزيّن بالمكسرات.", cuisine: "Egyptian", category: "Dessert", dishType: "Pudding", mainIngredient: "Rice", cookingTimeMinutes: 45, difficulty: "easy", vegetarian: true, spicy: false, mealType: "Dessert", prepTimeMinutes: 5, cookTimeMinutes: 40, totalTimeMinutes: 45, servings: 6, tags: ["egyptian", "dessert", "vegetarian", "make-ahead"], imageLabel: "ROZ BEL LABAN", imageBackground: "#92765a", imageAccent: "#e5b65c",
    ingredients: [
      ingredient("rice", "Egyptian short-grain rice", "أرز مصري", 100, "g", "Pudding", "الأرز"), ingredient("water", "Water", "مية", 300, "ml", "Pudding", "الأرز"), ingredient("milk", "Whole milk", "لبن كامل الدسم", 1, "liter", "Pudding", "اللبن"), ingredient("sugar", "Granulated sugar", "سكر", 120, "g", "Pudding", "التحلية"), ingredient("cornstarch", "Cornstarch", "نشا", 30, "g", "Pudding", "القوام"), ingredient("vanilla", "Vanilla", "فانيليا", 1, "teaspoon", "Flavor", "النكهة"), ingredient("mastic", "Ground mastic", "مستكة مطحونة", 0.25, "teaspoon", "Flavor", "النكهة", null, null, true), ingredient("pistachio", "Pistachios", "فستق", 30, "g", "Garnish", "التزيين", "chopped", "مفروم", true),
    ],
    steps: [
      step(1, "Soften the rice", "طرّي الأرز", "Rinse rice, place with water in a heavy saucepan, and simmer covered on low for 18 minutes until the grains split and the water is absorbed.", "اغسل الأرز وحطه مع المية في حلة تقيلة، وسيبه متغطي على نار هادية ١٨ دقيقة لحد ما الحبات تفتح والمية تتشرب.", 18, "Low", "هادية", "The rice is very soft and can be mashed against the pan with a spoon.", "الأرز طري جدًا وبيتداس بالمعلقة على جنب الحلة."),
      step(2, "Add the milk", "ضيف اللبن", "Whisk cornstarch into 100 ml cold milk. Add remaining milk, sugar, vanilla, and mastic to the rice and bring to a gentle simmer.", "دوب النشا في ١٠٠ مل لبن ساقع. ضيف باقي اللبن والسكر والفانيليا والمستكة للأرز ووصلها لغلوة هادية.", 8, "Medium", "متوسطة", "Steam rises and the milk moves slowly without boiling over.", "البخار طالع واللبن بيتحرك ببطء من غير ما يفور."),
      step(3, "Thicken slowly", "قلّب لحد ما يتقل", "Whisk in the cornstarch mixture. Stir continuously over medium-low for 10–12 minutes until the pudding coats the spoon but still pours.", "ضيف خليط النشا وقلّب باستمرار على نار متوسطة هادية ١٠–١٢ دقيقة لحد ما يغطي المعلقة ولسه يتصب.", 12, "Medium-low", "متوسطة هادية", "A line drawn through the pudding closes slowly and the surface looks glossy.", "الخط اللي بتعمله المعلقة يقفل ببطء والسطح يبقى لامع."),
      step(4, "Chill and garnish", "برّد وزيّن", "Pour into serving dishes, cover the surface, and chill at least 3 hours. Add pistachios just before serving.", "صب الأرز في أطباق التقديم وغطي السطح ودخله التلاجة ٣ ساعات على الأقل. حط الفستق قبل التقديم مباشرة.", 180, "Off heat", "من غير نار", "The pudding is cool and softly set, not rubbery, with a spoonable center.", "الأرز بارد وماسك نفسه بنعومة من غير ما يبقى مطاطي."),
    ],
  }),
  recipe({
    recipeId: "egyptian-hibiscus-drink", name: "Egyptian Hibiscus Tea", nameArabic: "كركديه مصري بارد", description: "Ruby hibiscus infusion balanced with sugar and lemon, served cold over ice.", descriptionArabic: "كركديه لونه ياقوتي متوازن بالسكر والليمون، بيتقدم ساقع على تلج.", cuisine: "Egyptian", category: "Drinks", dishType: "Cold drink", mainIngredient: "Hibiscus", cookingTimeMinutes: 20, difficulty: "easy", vegetarian: true, spicy: false, mealType: "Drink", prepTimeMinutes: 5, cookTimeMinutes: 15, totalTimeMinutes: 20, servings: 6, tags: ["egyptian", "drink", "non-alcoholic", "summer"], imageLabel: "HIBISCUS", imageBackground: "#713d52", imageAccent: "#e9a33e",
    ingredients: [
      ingredient("hibiscus", "Dried hibiscus petals", "كركديه ناشف", 50, "g", "Infusion", "النقع"), ingredient("water", "Water", "مية", 1.5, "liter", "Infusion", "النقع"), ingredient("sugar", "Granulated sugar", "سكر", 120, "g", "Sweetener", "التحلية"), ingredient("lemon", "Lemon juice", "عصير ليمون", 2, "tablespoons", "Finish", "اللمسة الأخيرة", null, null, true), ingredient("ice", "Ice", "تلج", 300, "g", "Serving", "التقديم", null, null, true, noSwap("Fresh ice", "تلج طازة")),
    ],
    steps: [
      step(1, "Rinse the petals", "اغسل الكركديه", "Rinse hibiscus quickly in a fine strainer to remove dust. Do not soak it for a long time or the color will become muddy.", "اشطف الكركديه بسرعة في مصفاة ناعمة عشان تشيل التراب. متسيبوش منقوع وقت طويل عشان اللون مايبقاش عكر.", 2, "No heat", "من غير نار", "The petals look clean and retain a deep burgundy color.", "البتلات نضيفة ولسه لونها نبيتي غامق."),
      step(2, "Infuse", "انقع الكركديه", "Bring water to a boil, turn off heat, add petals, and cover for 12 minutes. Strain without pressing the petals.", "اغلي المية واقفل النار وضيف الكركديه وغطيه ١٢ دقيقة. صفيه من غير ما تعصر البتلات.", 12, "Off heat", "من غير نار", "The liquid is ruby red and smells fruity, without a bitter aroma.", "السائل لونه أحمر ياقوتي وريحته فاكهية من غير مرارة."),
      step(3, "Sweeten and chill", "حلّي وبرّد", "Stir sugar into the hot infusion until dissolved. Add lemon if using, cool to room temperature, then refrigerate for at least 2 hours.", "قلّب السكر في المشروب السخن لحد ما يدوب. ضيف الليمون لو هتستخدمه، برده لحرارة الغرفة ودخله التلاجة ساعتين.", 120, "Off heat", "من غير نار", "No sugar crystals remain and the drink tastes tart before the ice is added.", "مفيش بلورات سكر والمشروب طعمه حامض خفيف قبل التلج."),
      step(4, "Serve", "قدّم", "Fill glasses with ice and pour over the chilled hibiscus. Stir once and serve immediately.", "املأ الكوبايات تلج وصب الكركديه الساقع. قلّب مرة وقدّمه فورًا.", 1, "Off heat", "من غير نار", "The drink is cold, clear, and bright rather than diluted.", "المشروب ساقع وصافي ولونه واضح من غير تخفيف زيادة."),
    ],
  }),
  recipe({
    recipeId: "egyptian-feteer-meshaltet", name: "Egyptian Feteer Meshaltet", nameArabic: "فطير مشلتت مصري", description: "Layered Egyptian pastry made from a supple dough, folded with ghee, and baked until flaky and golden.", descriptionArabic: "فطير مصري مورّق بعجينة طرية وطبقات سمنة، بيتخبز لحد ما يبقى مورّق ودهبي.", cuisine: "Egyptian", category: "Breakfast", dishType: "Pastry", mainIngredient: "Flour", cookingTimeMinutes: 70, difficulty: "hard", vegetarian: true, spicy: false, mealType: "Breakfast", prepTimeMinutes: 35, cookTimeMinutes: 35, totalTimeMinutes: 70, servings: 6, tags: ["egyptian", "breakfast", "pastry", "baking"], imageLabel: "FETEER", imageBackground: "#876247", imageAccent: "#e8b95a",
    ingredients: [
      ingredient("flour", "All-purpose flour", "دقيق", 500, "g", "Dough", "العجينة"), ingredient("water", "Warm water", "مية دافية", 300, "ml", "Dough", "العجينة"), ingredient("salt", "Fine salt", "ملح ناعم", 1, "teaspoon", "Dough", "العجينة"), ingredient("ghee", "Ghee or clarified butter", "سمنة بلدي", 150, "g", "Layers", "الطبقات"), ingredient("oil", "Neutral oil", "زيت نباتي", 2, "tablespoons", "Layers", "الطبقات"), ingredient("sugar", "Powdered sugar", "سكر بودرة", 2, "tablespoons", "Serving", "التقديم", null, null, true, noSwap("Powdered sugar", "سكر بودرة")), ingredient("honey", "Honey", "عسل", 60, "g", "Serving", "التقديم", null, null, true), ingredient("white-cheese", "White cheese", "جبنة بيضاء", 150, "g", "Serving", "التقديم", null, null, true),
    ],
    steps: [
      step(1, "Make the dough", "اعمل العجينة", "Mix flour and salt. Add water gradually and knead 8 minutes until smooth and elastic. Cover with oil and rest 20 minutes.", "اخلط الدقيق والملح. ضيف المية بالتدريج واعجن ٨ دقايق لحد ما تبقى ناعمة ومطاطة. غطيها بالزيت وسيبها ٢٠ دقيقة.", 28, "No heat", "من غير نار", "The dough stretches without tearing and feels soft, not sticky.", "العجينة بتتمط من غير ما تتقطع وطرية من غير لزوجة."),
      step(2, "Stretch and layer", "افرد واعمل الطبقات", "Divide into six balls. Oil the counter, stretch one ball paper-thin, brush with ghee, fold into a parcel, and repeat with the remaining balls.", "قسم العجينة ٦ كرات. ادهن الرخامة، افرد كرة رفيع جدًا، ادهنها بالسمنة، اطوِها كحزمة وكرر مع الباقي.", 20, "No heat", "من غير نار", "You can see the counter through the stretched dough and the ghee is evenly spread.", "تقدر تشوف الرخامة من خلال العجينة والسمنة متوزعة بالتساوي."),
      step(3, "Shape the pastry", "شكّل الفطير", "Stack the parcels, press gently into a thick round, and place in a greased 28 cm pan. Rest 10 minutes while the oven heats to 230°C.", "رص الحزم فوق بعض واضغط برفق لقرص سميك وحطه في صينية ٢٨ سم مدهونة. ريّحه ١٠ دقايق وسخّن الفرن على ٢٣٠°م.", 10, "No heat", "من غير نار", "The dough relaxes and fills the pan without springing back.", "العجينة بتهدى وتاخد شكل الصينية من غير ما ترجع تنكمش."),
      step(4, "Bake and serve", "اخبز وقدّم", "Bake 25–30 minutes until puffed and deep golden. Brush with a little ghee, rest 10 minutes, and serve with honey, cheese, or powdered sugar.", "اخبز ٢٥–٣٠ دقيقة لحد ما ينتفخ ولونه يبقى دهبي غامق. ادهنه بسمنة بسيطة، ريّحه ١٠ دقايق وقدمه بالعسل أو الجبنة أو السكر البودرة.", 40, "High", "عالية", "The top is crisp, the layers crackle when pressed, and the center is cooked through.", "الوش مقرمش والطبقات بتقرمش بالضغط والوسط مستوي."),
    ],
  }),
  recipe({
    recipeId: "egyptian-baked-eggplant", name: "Egyptian Baked Eggplant with Garlic", nameArabic: "باذنجان مصري بالثوم والخل", description: "Roasted eggplant dressed with garlic, cumin, vinegar, and parsley for a smoky Egyptian side dish.", descriptionArabic: "باذنجان مشوي ومتبل بالثوم والكمون والخل والبقدونس كطبق جانبي مصري بسيط.", cuisine: "Egyptian", category: "Side dish", dishType: "Roasted vegetables", mainIngredient: "Eggplant", cookingTimeMinutes: 40, difficulty: "easy", vegetarian: true, spicy: false, mealType: "Lunch", prepTimeMinutes: 10, cookTimeMinutes: 30, totalTimeMinutes: 40, servings: 4, tags: ["egyptian", "vegetarian", "side-dish", "vegetables"], imageLabel: "EGGPLANT", imageBackground: "#4f5e45", imageAccent: "#d49b4b",
    ingredients: [
      ingredient("eggplant", "Eggplants", "باذنجان", 3, "medium", "Main", "الأساسي", "halved lengthwise", "متقسم بالطول"), ingredient("garlic", "Garlic", "ثوم", 4, "cloves", "Dressing", "التتبيلة", "crushed", "مهروس"), ingredient("vinegar", "White vinegar", "خل أبيض", 3, "tablespoons", "Dressing", "التتبيلة"), ingredient("cumin", "Ground cumin", "كمون مطحون", 1, "teaspoon", "Dressing", "التتبيلة"), ingredient("parsley", "Fresh parsley", "بقدونس", 30, "g", "Garnish", "التزيين", "chopped", "مفروم"), ingredient("oil", "Olive oil", "زيت زيتون", 3, "tablespoons", "Cooking", "الطبخ"), ingredient("salt", "Fine salt", "ملح ناعم", 1, "teaspoon", "Dressing", "التتبيلة"), ingredient("chili", "Chili flakes", "شطة", 0.25, "teaspoon", "Dressing", "التتبيلة", null, null, true),
    ],
    steps: [
      step(1, "Salt the eggplant", "ملّح الباذنجان", "Score the cut side, sprinkle with half the salt, and rest 10 minutes. Pat dry so the surface roasts instead of steaming.", "اعمل شقوق في الناحية المقطوعة ورش نصف الملح وسيبه ١٠ دقايق. نشفه عشان يتحمر بدل ما يتبخر.", 10, "No heat", "من غير نار", "Moisture beads are removed and the flesh looks matte.", "الرطوبة اتشالت واللب شكله مطفي."),
      step(2, "Roast", "اشوي", "Heat oven to 230°C. Brush eggplant with oil, place cut-side down, and roast 20 minutes; turn and roast 8 minutes more.", "سخّن الفرن على ٢٣٠°م. ادهن الباذنجان بالزيت وحطه بالناحية المقطوعة لتحت ٢٠ دقيقة، اقلبه ٨ دقايق كمان.", 28, "High", "عالية", "The skin is wrinkled and the flesh collapses easily under a fork.", "الجلد كرمش واللب بيتهرس بسهولة بالشوكة."),
      step(3, "Mix the dressing", "اخلط التتبيلة", "Stir garlic, vinegar, cumin, remaining salt, and chili if using. Let it stand 3 minutes so the garlic mellows slightly.", "اخلط الثوم والخل والكمون وباقي الملح والشطة لو هتستخدمها. سيبها ٣ دقايق عشان الثوم يهدى.", 3, "No heat", "من غير نار", "The dressing smells sharp but the cumin rounds it out.", "ريحة التتبيلة حادة شوية والكمون موازنها."),
      step(4, "Dress and serve", "تبّل وقدّم", "Scoop the warm flesh into a dish, pour over the dressing and remaining oil, and finish with parsley. Serve warm or at room temperature.", "طلع اللب السخن في طبق وصب التتبيلة وباقي الزيت وزيّن بالبقدونس. قدمه دافي أو بدرجة حرارة الغرفة.", 3, "Off heat", "من غير نار", "The dressing coats the soft eggplant without pooling at the bottom.", "التتبيلة مغلفة الباذنجان من غير ما تتجمع تحت."),
    ],
  }),
  recipe({
    recipeId: "lebanese-hummus", name: "Lebanese Hummus", nameArabic: "حمص لبناني ناعم", description: "Silky chickpea hummus blended with tahini, lemon, and garlic, finished with olive oil and paprika.", descriptionArabic: "حمص ناعم جدًا بالطحينة والليمون والثوم، متقدم بزيت الزيتون والبابريكا.", cuisine: "Lebanese", category: "Side dish", dishType: "Dip", mainIngredient: "Chickpeas", cookingTimeMinutes: 15, difficulty: "easy", vegetarian: true, spicy: false, mealType: "Lunch", prepTimeMinutes: 10, cookTimeMinutes: 5, totalTimeMinutes: 15, servings: 4, tags: ["middle-eastern", "vegetarian", "dip", "quick"], imageLabel: "HUMMUS", imageBackground: "#a27c53", imageAccent: "#e0b14c",
    ingredients: [ingredient("chickpeas", "Cooked chickpeas", "حمص مسلوق", 500, "g", "Main", "الأساسي", "rinsed", "مغسول"), ingredient("tahini", "Tahini", "طحينة", 120, "g", "Sauce", "الصوص"), ingredient("lemon", "Lemon juice", "عصير ليمون", 60, "ml", "Sauce", "الصوص"), ingredient("garlic", "Garlic", "ثوم", 1, "clove", "Sauce", "الصوص"), ingredient("ice-water", "Ice water", "مية ساقعة", 100, "ml", "Texture", "القوام"), ingredient("olive-oil", "Olive oil", "زيت زيتون", 2, "tablespoons", "Garnish", "التزيين"), ingredient("paprika", "Paprika", "بابريكا", 0.5, "teaspoon", "Garnish", "التزيين", null, null, true), ingredient("pita", "Pita bread", "عيش شامي", 4, "pieces", "Serving", "التقديم", "warmed", "دافي", true), ingredient("salt", "Fine salt", "ملح ناعم", 1, "teaspoon", "Seasoning", "التتبيلة")],
    steps: [step(1, "Loosen the tahini", "خفف الطحينة", "Blend tahini, lemon, garlic, salt, and 60 ml water for 60 seconds until pale and creamy.", "اضرب الطحينة والليمون والثوم والملح و٦٠ مل مية دقيقة لحد ما اللون يفتح والقوام يبقى كريمي.", 1, "No heat", "من غير نار", "The tahini becomes pale and thick before becoming smooth.", "الطحينة لونها يفتح وتتقل قبل ما تنعم."), step(2, "Blend the chickpeas", "اضرب الحمص", "Add chickpeas and blend 2 minutes, scraping once. Add remaining water gradually until no graininess remains.", "ضيف الحمص واضرب دقيقتين واكشط الجوانب مرة. زود باقي المية تدريجيًا لحد ما القوام يبقى ناعم.", 3, "No heat", "من غير نار", "The hummus is smooth enough that no skins or lumps are visible.", "الحمص ناعم ومفيش قشر أو تكتلات باينة."), step(3, "Rest and adjust", "ريّح واضبط", "Rest for 5 minutes, taste, and add a few drops of lemon or a pinch of salt only if needed.", "سيبه ٥ دقايق، دوقه وضيف نقط ليمون أو رشة ملح بس لو محتاج.", 5, "No heat", "من غير نار", "The flavor is balanced and the surface holds a spoon track.", "الطعم متوازن والسطح يمسك أثر المعلقة."), step(4, "Serve", "قدّم", "Spread in a shallow dish, make a well, add olive oil, and dust with paprika. Serve with warm pita.", "افرد الحمص في طبق واسع واعمل تجويف وحط زيت الزيتون ورشة بابريكا. قدمه مع عيش شامي دافي.", 2, "No heat", "من غير نار", "The hummus stays thick on the plate while the oil gathers in the well.", "الحمص يفضل متماسك والزيت يتجمع في التجويف.")],
  }),
  recipe({
    recipeId: "indian-butter-chicken", name: "Indian Butter Chicken", nameArabic: "دجاج هندي بالزبدة", description: "Tender yogurt-marinated chicken simmered in a tomato, butter, and garam masala sauce.", descriptionArabic: "فراخ متتبلة بالزبادي في صوص طماطم بالزبدة والجارام ماسالا.", cuisine: "Indian", category: "Chicken", dishType: "Curry", mainIngredient: "Chicken", cookingTimeMinutes: 55, difficulty: "medium", vegetarian: false, spicy: true, mealType: "Dinner", prepTimeMinutes: 25, cookTimeMinutes: 30, totalTimeMinutes: 55, servings: 4, tags: ["indian", "chicken", "curry", "dinner"], imageLabel: "BUTTER CHICKEN", imageBackground: "#814538", imageAccent: "#e8b554",
    ingredients: [ingredient("chicken", "Boneless chicken thighs", "وراك فراخ مخلية", 700, "g", "Main", "الأساسي", "bite-size pieces", "قطع صغيرة"), ingredient("yogurt", "Plain yogurt", "زبادي", 120, "g", "Marinade", "التتبيلة"), ingredient("lemon", "Lemon juice", "عصير ليمون", 2, "tablespoons", "Marinade", "التتبيلة"), ingredient("garam-masala", "Garam masala", "جارام ماسالا", 2, "teaspoons", "Spices", "التوابل"), ingredient("tomato", "Crushed tomatoes", "طماطم مطحونة", 500, "g", "Sauce", "الصوص"), ingredient("butter", "Unsalted butter", "زبدة من غير ملح", 50, "g", "Sauce", "الصوص"), ingredient("cream", "Heavy cream", "كريمة طبخ", 120, "ml", "Sauce", "الصوص", null, null, true), ingredient("garlic", "Garlic", "ثوم", 4, "cloves", "Sauce", "الصوص"), ingredient("ginger", "Fresh ginger", "زنجبيل طازج", 1, "tablespoon", "Sauce", "الصوص"), ingredient("salt", "Fine salt", "ملح ناعم", 1.5, "teaspoons", "Seasoning", "التتبيلة"), ingredient("oil", "Neutral oil", "زيت نباتي", 1, "tablespoon", "Cooking", "الطبخ")],
    steps: [step(1, "Marinate", "تبّل", "Mix chicken with yogurt, lemon, half the garam masala, and half the salt. Cover and refrigerate 20 minutes.", "اخلط الفراخ مع الزبادي والليمون ونصف الجارام ماسالا ونصف الملح. غطيها ودخلها التلاجة ٢٠ دقيقة.", 20, "No heat", "من غير نار", "The marinade clings evenly and the chicken is chilled.", "التتبيلة مغلفة الفراخ كلها والفراخ باردة."), step(2, "Brown the chicken", "حمّر الفراخ", "Heat oil over medium-high and sear chicken in one layer for 3 minutes per side. Transfer while the center is still underdone.", "سخّن الزيت على نار متوسطة عالية وحمّر الفراخ في طبقة واحدة ٣ دقايق لكل ناحية. ارفعها وهي لسه مش مستوية بالكامل.", 8, "Medium-high", "متوسطة عالية", "The outside has browned patches without black spices.", "السطح فيه تحمير من غير ما التوابل تتحرق."), step(3, "Cook the sauce", "سوّي الصوص", "Melt butter over medium. Cook garlic and ginger 1 minute, add tomatoes, remaining spices and salt, and simmer uncovered for 12 minutes.", "دوب الزبدة على نار متوسطة. سوّي الثوم والزنجبيل دقيقة، ضيف الطماطم وباقي التوابل والملح وسيبها ١٢ دقيقة من غير غطا.", 15, "Medium", "متوسطة", "The sauce is thick, glossy, and no longer smells raw or metallic.", "الصوص تقيل ولامع وريحة الطماطم النيّة اختفت."), step(4, "Finish the curry", "كمّل الكاري", "Return chicken and juices, cover, and simmer 8 minutes. Stir in cream off heat if using; chicken must reach 74°C before serving.", "رجّع الفراخ والعصارة، غطي وسيبها ٨ دقايق. قلّب الكريمة بعد قفل النار لو هتستخدمها؛ لازم الفراخ توصل ٧٤°م.", 10, "Low", "هادية", "The chicken is opaque and tender, and the sauce coats it without splitting.", "الفراخ معتمة وطرية والصوص مغلفها من غير ما يفصل.")],
  }),
  recipe({
    recipeId: "japanese-chicken-teriyaki", name: "Japanese Chicken Teriyaki", nameArabic: "فراخ ترياكي ياباني", description: "Crisp-edged chicken thighs glazed with a balanced soy, ginger, and mirin sauce.", descriptionArabic: "وراك فراخ بجلد مقرمش ومغطاة بصوص صويا وزنجبيل وميرين متوازن.", cuisine: "Japanese", category: "Chicken", dishType: "Skillet", mainIngredient: "Chicken", cookingTimeMinutes: 35, difficulty: "easy", vegetarian: false, spicy: false, mealType: "Dinner", prepTimeMinutes: 10, cookTimeMinutes: 25, totalTimeMinutes: 35, servings: 4, tags: ["japanese", "chicken", "quick", "rice"], imageLabel: "TERIYAKI", imageBackground: "#465f5a", imageAccent: "#dc9b45",
    ingredients: [ingredient("chicken", "Bone-in chicken thighs", "وراك فراخ بالعظم", 900, "g", "Main", "الأساسي", "skin-on", "بالجلد"), ingredient("soy", "Soy sauce", "صوص صويا", 60, "ml", "Glaze", "الصوص"), ingredient("mirin", "Mirin", "ميرين", 60, "ml", "Glaze", "الصوص"), ingredient("sugar", "Brown sugar", "سكر بني", 1, "tablespoon", "Glaze", "الصوص"), ingredient("ginger", "Fresh ginger", "زنجبيل طازج", 1, "tablespoon", "Glaze", "الصوص", "grated", "مبشور"), ingredient("garlic", "Garlic", "ثوم", 1, "clove", "Glaze", "الصوص"), ingredient("oil", "Neutral oil", "زيت نباتي", 1, "teaspoon", "Cooking", "الطبخ"), ingredient("sesame", "Sesame seeds", "سمسم", 1, "teaspoon", "Garnish", "التزيين", null, null, true)],
    steps: [step(1, "Dry and season", "نشّف وتبّل", "Pat chicken very dry and season the flesh lightly. Whisk soy, mirin, sugar, ginger, and garlic in a bowl.", "نشّف الفراخ كويس وتبّل اللحم برشة بسيطة. اخلط الصويا والميرين والسكر والزنجبيل والثوم.", 5, "No heat", "من غير نار", "The skin is dry and the glaze sugar is mostly dissolved.", "الجلد ناشف والسكر داب أغلبه في الصوص."), step(2, "Crisp the skin", "قرمش الجلد", "Place chicken skin-side down in a cold skillet with oil. Heat to medium and cook 10–12 minutes, pressing once, until deeply golden.", "حط الفراخ والجلد لتحت في طاسة باردة مع الزيت. سخّنها على نار متوسطة ١٠–١٢ دقيقة واضغط مرة لحد ما الجلد يبقى دهبي غامق.", 12, "Medium", "متوسطة", "Fat has rendered and the skin releases from the pan without tearing.", "الدهون نزلت والجلد بيتشال من الطاسة من غير ما يتقطع."), step(3, "Cook through", "سوّي من الناحية التانية", "Turn chicken and cook 7–8 minutes until the thickest piece reaches 74°C. Pour off excess fat if needed.", "اقلب الفراخ وسيبها ٧–٨ دقايق لحد ما أسمك قطعة توصل ٧٤°م. صفي الدهون الزيادة لو موجودة.", 8, "Medium", "متوسطة", "The juices run clear and the meat is opaque beside the bone.", "العصارة شفافة واللحم معتم جنب العظمة."), step(4, "Glaze and rest", "غطّي بالصوص وريّح", "Add glaze and simmer 2–3 minutes, turning chicken once, until shiny and slightly syrupy. Rest 5 minutes and garnish with sesame.", "ضيف الصوص وسيبه ٢–٣ دقايق مع تقليب الفراخ مرة لحد ما يلمع ويتقل. ريّحها ٥ دقايق وزيّن بالسمسم.", 8, "Medium-low", "متوسطة هادية", "The glaze coats the spoon and does not burn at the edge of the pan.", "الصوص مغطي المعلقة ومش بيتحرق على أطراف الطاسة.")],
  }),
  recipe({
    recipeId: "mexican-chicken-tacos", name: "Mexican Chicken Tacos", nameArabic: "تاكو فراخ مكسيكي", description: "Juicy lime-chili chicken tucked into warm tortillas with cabbage, salsa, and avocado.", descriptionArabic: "فراخ بالليمون والشطة في تورتيلا دافية مع كرنب وصلصة وأفوكادو.", cuisine: "Mexican", category: "Chicken", dishType: "Tacos", mainIngredient: "Chicken", cookingTimeMinutes: 35, difficulty: "easy", vegetarian: false, spicy: true, mealType: "Dinner", prepTimeMinutes: 15, cookTimeMinutes: 20, totalTimeMinutes: 35, servings: 4, tags: ["mexican", "chicken", "street-food", "quick"], imageLabel: "TACOS", imageBackground: "#536044", imageAccent: "#e4a53f",
    ingredients: [ingredient("chicken", "Boneless chicken thighs", "وراك فراخ مخلية", 600, "g", "Main", "الأساسي", "thinly sliced", "شرائح رفيعة"), ingredient("lime", "Lime juice", "عصير ليمون أخضر", 3, "tablespoons", "Marinade", "التتبيلة"), ingredient("paprika", "Smoked paprika", "بابريكا مدخنة", 1, "teaspoon", "Spices", "التوابل"), ingredient("cumin", "Ground cumin", "كمون مطحون", 1, "teaspoon", "Spices", "التوابل"), ingredient("chili", "Chili powder", "شطة بودرة", 0.5, "teaspoon", "Spices", "التوابل"), ingredient("tortillas", "Corn tortillas", "تورتيلا ذرة", 12, "pieces", "Serving", "التقديم"), ingredient("cabbage", "Shredded cabbage", "كرنب مقطع", 200, "g", "Topping", "الإضافات"), ingredient("avocado", "Avocado", "أفوكادو", 1, "large", "Topping", "الإضافات", "sliced", "شرائح", true), ingredient("salsa", "Salsa", "صلصة", 180, "g", "Topping", "الإضافات", null, null, true), ingredient("oil", "Neutral oil", "زيت نباتي", 2, "tablespoons", "Cooking", "الطبخ"), ingredient("salt", "Fine salt", "ملح ناعم", 1, "teaspoon", "Seasoning", "التتبيلة")],
    steps: [step(1, "Season the chicken", "تبّل الفراخ", "Toss chicken with lime juice, paprika, cumin, chili, salt, and oil. Rest 10 minutes while the pan heats.", "قلّب الفراخ مع الليمون والبابريكا والكمون والشطة والملح والزيت. سيبها ١٠ دقايق والطاسة بتسخن.", 10, "No heat", "من غير نار", "The pieces are evenly coated and the lime smells fresh, not harsh.", "القطع متغطية والليمون ريحته فريش من غير حدة."), step(2, "Sear", "حمّر", "Heat a wide skillet over high. Cook chicken in one layer for 4–5 minutes per side, working in batches if crowded.", "سخّن طاسة واسعة على نار عالية. سوّي الفراخ في طبقة واحدة ٤–٥ دقايق لكل ناحية، وعلى دفعات لو الطاسة زحمة.", 10, "High", "عالية", "Edges are charred in spots and the center reaches 74°C.", "الأطراف فيها تحمير والداخل وصل ٧٤°م."), step(3, "Warm tortillas", "سخّن التورتيلا", "Warm tortillas in the dry skillet for 20 seconds per side and keep them wrapped in a clean towel.", "سخّن التورتيلا في الطاسة الناشفة ٢٠ ثانية لكل ناحية وخليها ملفوفة في فوطة نضيفة.", 5, "Medium", "متوسطة", "Each tortilla bends without cracking and has a few toasted spots.", "التورتيلا بتتني من غير ما تتكسر وعليها نقط تحمير."), step(4, "Assemble", "ركّب التاكو", "Fill each tortilla with chicken and cabbage. Add avocado and salsa if using, fold, and serve while hot.", "احشي كل تورتيلا بالفراخ والكرنب. ضيف الأفوكادو والصلصة لو هتستخدمهم، اطوي وقدّم وهو سخن.", 5, "Off heat", "من غير نار", "The tortilla stays flexible and the filling is hot without becoming watery.", "التورتيلا طرية والحشوة سخنة من غير مية زيادة.")],
  }),
  recipe({
    recipeId: "korean-beef-bulgogi", name: "Korean Beef Bulgogi", nameArabic: "بولجوجي لحمة كوري", description: "Thin beef slices marinated with pear, soy, garlic, and sesame, then seared quickly for caramelized edges.", descriptionArabic: "شرائح لحمة رفيعة متتبلة بالكمثرى والصويا والثوم والسمسم ومتحمرة بسرعة.", cuisine: "Korean", category: "Meat", dishType: "Stir-fry", mainIngredient: "Beef", cookingTimeMinutes: 35, difficulty: "medium", vegetarian: false, spicy: false, mealType: "Dinner", prepTimeMinutes: 25, cookTimeMinutes: 10, totalTimeMinutes: 35, servings: 4, tags: ["korean", "beef", "quick", "rice"], imageLabel: "BULGOGI", imageBackground: "#4e5b54", imageAccent: "#d88c48",
    ingredients: [ingredient("beef", "Beef sirloin", "شرائح ستيك لحمة", 600, "g", "Main", "الأساسي", "thinly sliced", "شرائح رفيعة"), ingredient("pear", "Asian pear", "كمثرى آسيوية", 0.5, "large", "Marinade", "التتبيلة", "grated", "مبشورة"), ingredient("soy", "Soy sauce", "صوص صويا", 60, "ml", "Marinade", "التتبيلة"), ingredient("sesame-oil", "Sesame oil", "زيت سمسم", 1, "tablespoon", "Marinade", "التتبيلة"), ingredient("sugar", "Brown sugar", "سكر بني", 1, "tablespoon", "Marinade", "التتبيلة"), ingredient("garlic", "Garlic", "ثوم", 4, "cloves", "Marinade", "التتبيلة"), ingredient("onion", "Yellow onion", "بصلة", 1, "medium", "Vegetables", "الخضار", "sliced", "شرائح"), ingredient("rice", "Cooked rice", "أرز مطبوخ", 600, "g", "Serving", "التقديم", null, null, true), ingredient("scallion", "Scallions", "بصل أخضر", 3, "pieces", "Garnish", "التزيين", "sliced", "شرائح", true), ingredient("sesame", "Sesame seeds", "سمسم", 1, "tablespoon", "Garnish", "التزيين", null, null, true)],
    steps: [step(1, "Marinate", "تبّل", "Combine pear, soy, sesame oil, sugar, garlic, and beef. Cover and refrigerate for 20 minutes; do not exceed overnight because the pear tenderizes quickly.", "اخلط الكمثرى والصويا وزيت السمسم والسكر والثوم واللحمة. غطيها ودخلها التلاجة ٢٠ دقيقة؛ متسيبهاش أكتر من ليلة عشان الكمثرى بتطرّي بسرعة.", 20, "No heat", "من غير نار", "The marinade coats each slice and the meat remains firm enough to lift.", "التتبيلة مغلفة كل شريحة واللحمة لسه متماسكة وقت الرفع."), step(2, "Heat the pan", "سخّن الطاسة", "Heat a wide pan until very hot. Add onion and cook 2 minutes until just softened, then transfer it out.", "سخّن طاسة واسعة جدًا. سوّي البصل دقيقتين لحد ما يطرى بسيط وبعدين ارفعه.", 2, "High", "عالية", "The onion has browned edges but still has a little bite.", "البصل اتحمر من الأطراف ولسه فيه قوام."), step(3, "Sear the beef", "حمّر اللحمة", "Add beef in small batches and sear 60–90 seconds per side. Return onion and cook 1 minute more; the beef should reach 63°C minimum.", "حط اللحمة على دفعات صغيرة وحمّرها ٦٠–٩٠ ثانية لكل ناحية. رجّع البصل دقيقة؛ اللحمة لازم توصل ٦٣°م على الأقل.", 7, "High", "عالية", "Edges are caramelized and the slices remain juicy, not gray and stewed.", "الأطراف مكرملة والشرائح طرية مش رمادي ومسلوقة."), step(4, "Finish", "قدّم", "Scatter scallions and sesame if using. Serve immediately over rice, keeping the pan uncovered so the edges stay caramelized.", "رش البصل الأخضر والسمسم لو هتستخدمهم. قدم فورًا فوق الأرز وخلي الطاسة من غير غطا عشان التحمير يفضل واضح.", 2, "Off heat", "من غير نار", "The glaze clings to the beef and the garnish stays crisp.", "الصوص ماسك في اللحمة والإضافة لسه مقرمشة.")],
  }),
  recipe({
    recipeId: "egyptian-fattah", name: "Egyptian Fattah", nameArabic: "فتة مصرية بالخل والثوم", description: "Layered Egyptian fattah with toasted bread, seasoned rice, garlicky vinegar sauce, and tender beef broth.", descriptionArabic: "فتة مصرية بطبقات العيش المحمص والأرز وصوص الخل والثوم مع شوربة لحمة غنية.", cuisine: "Egyptian", category: "Meat", dishType: "Layered rice dish", mainIngredient: "Beef", cookingTimeMinutes: 105, difficulty: "medium", vegetarian: false, spicy: false, mealType: "Dinner", prepTimeMinutes: 25, cookTimeMinutes: 80, totalTimeMinutes: 105, servings: 6, tags: ["egyptian", "beef", "rice", "celebration"], imageLabel: "FATTAH", imageBackground: "#76533f", imageAccent: "#e1aa4c",
    ingredients: [ingredient("beef", "Beef chuck", "لحمة كندوز", 900, "g", "Meat", "اللحمة", "large cubes", "مكعبات كبيرة"), ingredient("rice", "Egyptian rice", "أرز مصري", 300, "g", "Rice", "الأرز", "rinsed", "مغسول"), ingredient("bread", "Baladi bread", "عيش بلدي", 3, "pieces", "Bread", "العيش", "cubed", "مكعبات"), ingredient("stock", "Beef stock", "شوربة لحمة", 1.2, "liter", "Broth", "الشوربة"), ingredient("garlic", "Garlic", "ثوم", 8, "cloves", "Sauce", "الصوص", "minced", "مفروم"), ingredient("vinegar", "White vinegar", "خل أبيض", 5, "tablespoons", "Sauce", "الصوص"), ingredient("tomato", "Tomato sauce", "صلصة طماطم", 400, "g", "Sauce", "الصوص"), ingredient("oil", "Neutral oil", "زيت نباتي", 4, "tablespoons", "Cooking", "الطبخ"), ingredient("cumin", "Ground cumin", "كمون مطحون", 1, "teaspoon", "Seasoning", "التتبيلة"), ingredient("cardamom", "Cardamom pods", "حبهان", 3, "pieces", "Broth", "الشوربة"), ingredient("salt", "Fine salt", "ملح ناعم", 2, "teaspoons", "Seasoning", "التتبيلة"), ingredient("pepper", "Black pepper", "فلفل أسود", 1, "teaspoon", "Seasoning", "التتبيلة")],
    steps: [step(1, "Cook the beef", "سوّي اللحمة", "Put beef, stock, cardamom, half the salt, and pepper in a pot. Bring to a boil, skim the foam, cover, and simmer on low for 70 minutes until a fork enters easily.", "حط اللحمة والشوربة والحبهان ونصف الملح والفلفل في حلة. اغليها وشيل الرغوة، غطيها وسيبها على نار هادية ٧٠ دقيقة لحد ما الشوكة تدخل بسهولة.", 70, "Low", "هادية", "The broth is clear and the beef is tender but still holds its shape.", "الشوربة صافية واللحمة طرية ولسه محافظة على شكلها."), step(2, "Cook rice and bread", "سوّي الأرز وحمّص العيش", "Cook rinsed rice with 450 ml broth and a pinch of salt, covered on low for 18 minutes. Toss bread with 2 tablespoons oil and toast at 200°C for 10 minutes until crisp.", "سوّي الأرز مع ٤٥٠ مل شوربة ورشة ملح، متغطي على نار هادية ١٨ دقيقة. قلّب العيش مع ملعقتين زيت وحمّصه على ٢٠٠°م ١٠ دقايق لحد ما يقرمش.", 28, "Low", "هادية", "Rice is fluffy and bread cubes are crisp at the edges.", "الأرز مفلفل ومكعبات العيش مقرمشة من الأطراف."), step(3, "Make the sauces", "حضّر الصوصات", "Fry half the garlic in 1 tablespoon oil for 30 seconds. Add vinegar and 150 ml broth, simmer 3 minutes, and season. Simmer tomato sauce separately for 8 minutes with cumin.", "شوّح نصف الثوم في ملعقة زيت ٣٠ ثانية. ضيف الخل و١٥٠ مل شوربة وسيبهم ٣ دقايق وتبّل. سخّن صلصة الطماطم لوحدها ٨ دقايق مع الكمون.", 11, "Medium", "متوسطة", "The vinegar sauce smells sharp but cooked, and the tomato sauce coats a spoon.", "ريحة صوص الخل حادة بس مستوية وصلصة الطماطم بتغطي المعلقة."), step(4, "Layer and serve", "رصّ وقدّم", "Layer toasted bread, a little vinegar sauce, rice, beef, tomato sauce, and the remaining garlic sauce. Serve immediately so the bread keeps some crunch.", "رص العيش المحمص ورشة من صوص الخل والأرز واللحمة وصلصة الطماطم وباقي صوص الثوم. قدم فورًا عشان العيش يفضل فيه قرمشة.", 6, "Off heat", "من غير نار", "The layers remain distinct, the beef is hot, and the bread is crisp at the edges.", "الطبقات باينة واللحمة سخنة والعيش مقرمش من الأطراف." )],
  }),
  recipe({
    recipeId: "italian-eggplant-parmigiana", name: "Italian Eggplant Parmigiana", nameArabic: "باذنجان بارميجيانا إيطالي", description: "Roasted eggplant layered with basil tomato sauce, mozzarella, and Parmesan until bubbling and tender.", descriptionArabic: "طبقات باذنجان مشوي وصلصة طماطم بالريحان وموتزاريلا وبارميزان لحد ما تسيح وتتحمر.", cuisine: "Italian", category: "Vegetables", dishType: "Baked casserole", mainIngredient: "Eggplant", cookingTimeMinutes: 70, difficulty: "medium", vegetarian: true, spicy: false, mealType: "Dinner", prepTimeMinutes: 20, cookTimeMinutes: 50, totalTimeMinutes: 70, servings: 6, tags: ["italian", "vegetarian", "baked", "comfort-food"], imageLabel: "PARMIGIANA", imageBackground: "#586044", imageAccent: "#d98050",
    ingredients: [ingredient("eggplant", "Eggplants", "باذنجان", 3, "medium", "Layers", "الطبقات", "sliced", "شرائح"), ingredient("tomato", "Crushed tomatoes", "طماطم مطحونة", 700, "g", "Sauce", "الصلصة"), ingredient("onion", "Yellow onion", "بصلة", 1, "medium", "Sauce", "الصلصة"), ingredient("garlic", "Garlic", "ثوم", 3, "cloves", "Sauce", "الصلصة"), ingredient("mozzarella", "Mozzarella", "موتزاريلا", 250, "g", "Cheese", "الجبنة"), ingredient("parmesan", "Parmesan", "بارميزان", 60, "g", "Cheese", "الجبنة"), ingredient("basil", "Fresh basil", "ريحان طازة", 20, "g", "Sauce", "الصلصة"), ingredient("olive-oil", "Olive oil", "زيت زيتون", 5, "tablespoons", "Cooking", "الطبخ"), ingredient("salt", "Fine salt", "ملح ناعم", 2, "teaspoons", "Seasoning", "التتبيلة")],
    steps: [step(1, "Roast eggplant", "اشوي الباذنجان", "Heat oven to 220°C. Brush slices with oil and roast 15 minutes per side until tender and lightly browned.", "سخّن الفرن على ٢٢٠°م. ادهن الشرائح بالزيت واشويها ١٥ دقيقة لكل ناحية لحد ما تطرى وتتحمر خفيف.", 30, "High", "عالية", "The slices are flexible and no longer spongy in the center.", "الشرائح طرية ومفيهاش قوام إسفنجي في النص."), step(2, "Make tomato sauce", "اعمل صلصة الطماطم", "Cook onion in 1 tablespoon oil for 5 minutes. Add garlic for 30 seconds, tomatoes, salt, and basil; simmer uncovered 15 minutes.", "سوّي البصل في ملعقة زيت ٥ دقايق. ضيف الثوم ٣٠ ثانية والطماطم والملح والريحان وسيبها ١٥ دقيقة من غير غطا.", 21, "Medium-low", "متوسطة هادية", "The sauce is thick enough to mound on a spoon and smells sweet.", "الصلصة تقيلة على المعلقة وريحتهـا حلوة."), step(3, "Layer", "رصّ الطبقات", "Heat oven to 190°C. Spread sauce, eggplant, mozzarella, and Parmesan in three layers, finishing with cheese and a little oil.", "سخّن الفرن على ١٩٠°م. رص صلصة وباذنجان وموتزاريلا وبارميزان في ٣ طبقات، وأنهِ بالجبنة وشوية زيت.", 10, "No heat", "من غير نار", "Every eggplant slice is covered and cheese reaches the edges.", "كل شريحة متغطية والجبنة واصلة للأطراف."), step(4, "Bake and rest", "اخبز وريّح", "Bake 25 minutes until bubbling, then broil 3 minutes until browned. Rest 15 minutes before slicing.", "اخبز ٢٥ دقيقة لحد ما تغلي، وبعدين حمّر ٣ دقايق. ريّحها ١٥ دقيقة قبل التقطيع.", 43, "Medium-high", "متوسطة عالية", "Cheese is bubbling and browned, and the layers slice without releasing watery sauce.", "الجبنة بتغلي ومتحمرة والطبقات بتتقطع من غير صوص مائي." )],
  }),
  recipe({
    recipeId: "thai-green-curry", name: "Thai Green Curry with Vegetables", nameArabic: "كاري أخضر تايلاندي بالخضار", description: "Fragrant coconut curry with vegetables, basil, and lime served over steamed jasmine rice.", descriptionArabic: "كاري جوز هند أخضر عطري بالخضار والريحان والليمون الأخضر مع أرز ياسمين.", cuisine: "Thai", category: "Vegetables", dishType: "Curry", mainIngredient: "Vegetables", cookingTimeMinutes: 35, difficulty: "medium", vegetarian: true, spicy: true, mealType: "Dinner", prepTimeMinutes: 15, cookTimeMinutes: 20, totalTimeMinutes: 35, servings: 4, tags: ["thai", "vegetarian", "curry", "rice"], imageLabel: "GREEN CURRY", imageBackground: "#4e654f", imageAccent: "#e1a647",
    ingredients: [ingredient("paste", "Green curry paste", "معجون كاري أخضر", 3, "tablespoons", "Curry", "الكاري"), ingredient("coconut", "Coconut milk", "لبن جوز هند", 800, "ml", "Curry", "الكاري"), ingredient("tofu", "Firm tofu", "توفو متماسك", 300, "g", "Main", "الأساسي", "cubed", "مكعبات"), ingredient("eggplant", "Thai eggplant or zucchini", "باذنجان تايلاندي أو كوسة", 300, "g", "Vegetables", "الخضار", "quartered", "أرباع"), ingredient("pepper", "Red bell pepper", "فلفل رومي أحمر", 1, "large", "Vegetables", "الخضار", "sliced", "شرائح"), ingredient("green-beans", "Green beans", "فاصوليا خضراء", 200, "g", "Vegetables", "الخضار"), ingredient("fish-sauce", "Fish sauce", "صوص سمك", 2, "tablespoons", "Seasoning", "التتبيلة", null, null, true), ingredient("sugar", "Brown sugar", "سكر بني", 1, "tablespoon", "Seasoning", "التتبيلة"), ingredient("lime", "Lime juice", "عصير ليمون أخضر", 2, "tablespoons", "Finish", "التقديم"), ingredient("basil", "Thai basil", "ريحان تايلاندي", 20, "g", "Garnish", "التزيين", null, null, true), ingredient("rice", "Jasmine rice", "أرز ياسمين", 300, "g", "Serving", "التقديم", null, null, true)],
    steps: [step(1, "Fry the paste", "حمّر المعجون", "Spoon the thick top of the coconut milk into a pot and simmer over medium-high for 3 minutes. Stir in curry paste and cook 2 minutes.", "خد الجزء التقيل من فوق لبن جوز الهند وسيبه ٣ دقايق على نار متوسطة عالية. ضيف معجون الكاري وسيبه دقيقتين.", 5, "Medium-high", "متوسطة عالية", "The paste smells fragrant and the coconut fat looks glossy around it.", "ريحة المعجون طالعة ودهن جوز الهند لامع حواليه."), step(2, "Simmer the vegetables", "سوّي الخضار", "Add remaining coconut milk, sugar, fish sauce if using, eggplant, pepper, and beans. Simmer uncovered 10 minutes.", "ضيف باقي لبن جوز الهند والسكر وصوص السمك لو هتستخدمه والباذنجان والفلفل والفاصوليا. سيبها ١٠ دقايق من غير غطا.", 10, "Medium", "متوسطة", "The vegetables are tender at the edges but still hold their color and shape.", "الخضار طرية من الأطراف ولسه محتفظة بلونها وشكلها."), step(3, "Warm the tofu", "سخّن التوفو", "Fold in tofu and simmer 5 minutes without hard boiling so it absorbs sauce without crumbling.", "قلب التوفو وسيبه ٥ دقايق من غير غليان جامد عشان يشرب الصوص من غير ما يتفتت.", 5, "Low", "هادية", "The tofu is hot in the center and remains in clean cubes.", "التوفو سخن من جوه ولسه مكعبات متماسكة."), step(4, "Brighten and serve", "ظبط وقدّم", "Turn off heat, stir in lime juice and basil, and serve immediately over jasmine rice.", "اقفل النار وقلّب عصير الليمون والريحان وقدّم فورًا فوق أرز الياسمين.", 3, "Off heat", "من غير نار", "The curry is creamy, bright, and spicy without a separated oily layer.", "الكاري كريمي ومنعش وحار من غير طبقة زيت منفصلة.")],
  }),
  recipe({
    recipeId: "egyptian-kebda-eskandarani", name: "Alexandrian Liver", nameArabic: "كبدة إسكندراني", description: "Thin beef liver quickly seared with garlic, green chili, cumin, and vinegar in the Alexandrian street-food style.", descriptionArabic: "شرائح كبدة رفيعة متحمرة بسرعة بالثوم والفلفل الأخضر والكمون والخل على طريقة إسكندرية.", cuisine: "Egyptian", category: "Meat", dishType: "Skillet", mainIngredient: "Beef liver", cookingTimeMinutes: 30, difficulty: "medium", vegetarian: false, spicy: true, mealType: "Dinner", prepTimeMinutes: 15, cookTimeMinutes: 15, totalTimeMinutes: 30, servings: 4, tags: ["egyptian", "alexandrian", "street-food", "beef"], imageLabel: "KEBDA", imageBackground: "#664941", imageAccent: "#e0a04a",
    ingredients: [ingredient("liver", "Beef liver", "كبدة بقري", 600, "g", "Main", "الأساسي", "thinly sliced", "شرائح رفيعة"), ingredient("garlic", "Garlic", "ثوم", 6, "cloves", "Marinade", "التتبيلة", "minced", "مفروم"), ingredient("pepper", "Green chili peppers", "فلفل أخضر حار", 3, "pieces", "Seasoning", "التتبيلة", "sliced", "شرائح"), ingredient("vinegar", "White vinegar", "خل أبيض", 3, "tablespoons", "Marinade", "التتبيلة"), ingredient("lemon", "Lemon juice", "عصير ليمون", 2, "tablespoons", "Marinade", "التتبيلة"), ingredient("cumin", "Ground cumin", "كمون مطحون", 2, "teaspoons", "Seasoning", "التتبيلة"), ingredient("coriander", "Ground coriander", "كزبرة ناشفة", 1, "teaspoon", "Seasoning", "التتبيلة"), ingredient("oil", "Neutral oil", "زيت نباتي", 4, "tablespoons", "Cooking", "الطبخ"), ingredient("salt", "Fine salt", "ملح ناعم", 1.5, "teaspoons", "Seasoning", "التتبيلة"), ingredient("bread", "Baladi bread", "عيش بلدي", 4, "pieces", "Serving", "التقديم", null, null, true), ingredient("pickles", "Pickles", "مخلل", 200, "g", "Serving", "التقديم", null, null, true)],
    steps: [step(1, "Prepare the liver", "جهّز الكبدة", "Pat liver very dry and cut into thin strips no thicker than 5 mm. Mix with half the garlic, vinegar, lemon, cumin, coriander, and salt for 10 minutes only.", "نشف الكبدة كويس وقطعها شرائح رفيعة بسمك لا يزيد عن ٥ مم. اخلطها مع نصف الثوم والخل والليمون والكمون والكزبرة والملح ١٠ دقايق بس.", 10, "No heat", "من غير نار", "The strips are evenly coated but still firm; a long marinade would make them mushy.", "الشرائح متغطية ولسه متماسكة؛ التتبيل الطويل يخليها مهروسة."), step(2, "Heat the skillet", "سخّن الطاسة", "Heat oil in a wide skillet over high heat until shimmering. Add chili and remaining garlic and stir for 30 seconds without browning the garlic.", "سخّن الزيت في طاسة واسعة على نار عالية لحد ما يلمع. ضيف الفلفل وباقي الثوم وقلّب ٣٠ ثانية من غير ما تحرق الثوم.", 1, "High", "عالية", "The chili smells bright and the garlic is pale gold, not brown.", "ريحة الفلفل واضحة والثوم دهبي فاتح مش بني."), step(3, "Sear in batches", "حمّر على دفعات", "Add liver in one loose layer and sear 2 minutes per side. Work in batches so the pan stays hot; the thickest strip should reach 71°C.", "حط الكبدة في طبقة واحدة وسيبها دقيقتين لكل ناحية. اشتغل على دفعات عشان الطاسة تفضل سخنة؛ أسمك شريحة لازم توصل ٧١°م.", 8, "High", "عالية", "The outside is browned, the center is just opaque, and the strips remain juicy.", "السطح اتحمر والداخل بقى معتم ولسه الشرائح طرية."), step(4, "Finish and serve", "كمّل وقدّم", "Return all liver to the skillet for 1 minute, taste for salt, and serve immediately with warm baladi bread and pickles if available.", "رجّع كل الكبدة للطاسة دقيقة، دوق الملح وقدّم فورًا مع عيش بلدي دافي ومخلل لو موجود.", 2, "Medium", "متوسطة", "The pan juices cling to the liver and the bread is ready for scooping.", "العصارة ماسكة في الكبدة والعيش جاهز للتغميس." )],
  }),
  recipe({
    recipeId: "egyptian-chicken-orzo-soup", name: "Egyptian Chicken Orzo Soup", nameArabic: "شوربة لسان عصفور بالفراخ", description: "Comforting chicken soup with toasted orzo, carrot, celery, and lemon, finished with parsley.", descriptionArabic: "شوربة فراخ دافية بلسان العصفور المحمص والجزر والكرفس ولمسة ليمون وبقدونس.", cuisine: "Egyptian", category: "Soup", dishType: "One-pot soup", mainIngredient: "Chicken", cookingTimeMinutes: 50, difficulty: "easy", vegetarian: false, spicy: false, mealType: "Lunch", prepTimeMinutes: 15, cookTimeMinutes: 35, totalTimeMinutes: 50, servings: 4, tags: ["egyptian", "soup", "chicken", "comfort-food"], imageLabel: "ORZO SOUP", imageBackground: "#59624b", imageAccent: "#dca34b",
    ingredients: [ingredient("chicken", "Boneless chicken breast", "صدور فراخ مخلية", 500, "g", "Main", "الأساسي", "cubed", "مكعبات"), ingredient("orzo", "Orzo pasta", "لسان عصفور", 150, "g", "Pasta", "المكرونة"), ingredient("carrot", "Carrot", "جزرة", 2, "medium", "Vegetables", "الخضار", "diced", "مكعبات"), ingredient("celery", "Celery", "كرفس", 2, "sticks", "Vegetables", "الخضار", "diced", "مكعبات"), ingredient("onion", "Yellow onion", "بصلة", 1, "medium", "Vegetables", "الخضار", "diced", "مكعبات"), ingredient("stock", "Chicken stock", "شوربة فراخ", 1.2, "liter", "Broth", "الشوربة"), ingredient("lemon", "Lemon juice", "عصير ليمون", 2, "tablespoons", "Finish", "التقديم"), ingredient("parsley", "Fresh parsley", "بقدونس", 30, "g", "Garnish", "التزيين", "chopped", "مفروم", true), ingredient("oil", "Olive oil", "زيت زيتون", 2, "tablespoons", "Cooking", "الطبخ"), ingredient("salt", "Fine salt", "ملح ناعم", 1.5, "teaspoons", "Seasoning", "التتبيلة"), ingredient("pepper", "Black pepper", "فلفل أسود", 0.5, "teaspoon", "Seasoning", "التتبيلة")],
    steps: [step(1, "Toast the pasta", "حمّص لسان العصفور", "Toast orzo in oil over medium for 3–4 minutes until lightly golden, then transfer it out.", "حمّص لسان العصفور في الزيت على نار متوسطة ٣–٤ دقايق لحد ما يبقى دهبي فاتح، وطلعه.", 4, "Medium", "متوسطة", "The pasta smells nutty and is evenly pale gold.", "المكرونة ريحتها محمصة ولونها دهبي فاتح بالتساوي."), step(2, "Soften vegetables", "طرّي الخضار", "Cook onion, carrot, and celery with a pinch of salt for 6 minutes until glossy and slightly tender.", "سوّي البصل والجزر والكرفس مع رشة ملح ٦ دقايق لحد ما يلمعوا ويطروا بسيط.", 6, "Medium", "متوسطة", "The vegetables bend when pressed with a spoon.", "الخضار بيتني لما تضغط عليه بالمعلقة."), step(3, "Simmer", "سوّي الشوربة", "Add stock, chicken, pepper, and orzo. Boil, cover, reduce to low, and simmer 18 minutes, stirring once at 10 minutes.", "ضيف الشوربة والفراخ والفلفل ولسان العصفور. اغليها وغطيها وطي النار ١٨ دقيقة مع تقليبة بعد ١٠ دقايق.", 18, "Low", "هادية", "Chicken reaches 74°C and orzo is tender without falling apart.", "الفراخ وصلت ٧٤°م ولسان العصفور طري من غير ما يتهرى."), step(4, "Brighten and serve", "ظبط وقدّم", "Turn off heat, stir in lemon, taste for salt, rest covered 3 minutes, and finish with parsley.", "اقفل النار وقلّب الليمون ودوق الملح وسيبها متغطية ٣ دقايق وزيّن بالبقدونس.", 3, "Off heat", "من غير نار", "The broth is clear and the lemon smells fresh.", "الشوربة صافية وريحة الليمون فريش.")],
  }),
  recipe({
    recipeId: "egyptian-carrot-orange-salad", name: "Egyptian Carrot and Orange Salad", nameArabic: "سلطة جزر وبرتقال مصرية", description: "Crunchy carrot ribbons and orange segments with cumin, mint, and lemon dressing.", descriptionArabic: "شرائح جزر مقرمشة وقطع برتقال بالكمون والنعناع وتتبيلة ليمون خفيفة.", cuisine: "Egyptian", category: "Side dish", dishType: "Salad", mainIngredient: "Carrot", cookingTimeMinutes: 15, difficulty: "easy", vegetarian: true, spicy: false, mealType: "Lunch", prepTimeMinutes: 15, cookTimeMinutes: 0, totalTimeMinutes: 15, servings: 4, tags: ["egyptian", "salad", "vegetarian", "quick"], imageLabel: "CARROT SALAD", imageBackground: "#57705b", imageAccent: "#e2a044",
    ingredients: [ingredient("carrot", "Carrots", "جزر", 500, "g", "Salad", "السلطة", "ribboned", "شرائح طويلة"), ingredient("orange", "Oranges", "برتقال", 2, "large", "Salad", "السلطة", "peeled and segmented", "مقشر ومتقطع فصوص"), ingredient("mint", "Fresh mint", "نعناع فريش", 20, "g", "Herbs", "الخضرة", "torn", "مقطع باليد"), ingredient("lemon", "Lemon juice", "عصير ليمون", 2, "tablespoons", "Dressing", "التتبيلة"), ingredient("olive-oil", "Olive oil", "زيت زيتون", 3, "tablespoons", "Dressing", "التتبيلة"), ingredient("cumin", "Ground cumin", "كمون مطحون", 1, "teaspoon", "Dressing", "التتبيلة"), ingredient("honey", "Honey", "عسل", 1, "teaspoon", "Dressing", "التتبيلة", null, null, true), ingredient("salt", "Fine salt", "ملح ناعم", 0.5, "teaspoon", "Dressing", "التتبيلة")],
    steps: [step(1, "Prepare produce", "جهّز الخضار", "Peel carrots into ribbons and remove the bitter white pith from the orange before separating its segments.", "قشر الجزر لشرائح طويلة وشيل القشر الأبيض المر من البرتقال قبل فصل الفصوص.", 8, "No heat", "من غير نار", "Ribbons bend easily and no white pith remains.", "شرائح الجزر بتتني ومفيش قشر أبيض باقي."), step(2, "Whisk dressing", "اخلط التتبيلة", "Whisk lemon juice, orange juice, olive oil, cumin, salt, and honey if using until glossy.", "اضرب عصير الليمون والبرتقال والزيت والكمون والملح والعسل لو هتستخدمه لحد ما تتجانس.", 2, "No heat", "من غير نار", "The cumin is dispersed and the dressing does not separate immediately.", "الكمون متوزع والتتبيلة مش بتفصل فورًا."), step(3, "Toss gently", "قلّب بالراحة", "Toss carrots, orange, and mint with dressing using two forks so the orange segments stay whole.", "قلّب الجزر والبرتقال والنعناع بالتتبيلة باستخدام شوكتين عشان الفصوص تفضل سليمة.", 3, "No heat", "من غير نار", "Every ribbon is lightly coated without liquid pooling.", "كل شريحة متغطية خفيف من غير سائل متجمع."), step(4, "Rest and serve", "ريّح وقدّم", "Rest 2 minutes for the carrot to soften slightly, then serve beside grilled food.", "سيبها دقيقتين عشان الجزر يطرى بسيط، وقدّمها جنب الأكل المشوي.", 2, "No heat", "من غير نار", "The carrots remain crisp and the citrus aroma is bright.", "الجزر لسه مقرمش وريحة الحمضيات واضحة.")],
  }),
];

function assertRecipeQuality(recipes: InsertRecipe[]) {
  const recipeIds = new Set<string>();

  for (const recipe of recipes) {
    if (recipeIds.has(recipe.recipeId)) throw new Error(`Duplicate recipe ID: ${recipe.recipeId}`);
    recipeIds.add(recipe.recipeId);

    const requiredText = [recipe.recipeId, recipe.name, recipe.nameArabic, recipe.description, recipe.descriptionArabic, recipe.cuisine, recipe.category, recipe.mealType, recipe.difficulty];
    if (requiredText.some((value) => !value?.trim())) throw new Error(`Incomplete metadata: ${recipe.recipeId}`);
    if (!recipe.imageUrl?.trim() || !recipe.tags?.length) throw new Error(`Missing image or tags: ${recipe.recipeId}`);
    if (recipe.totalTimeMinutes !== recipe.prepTimeMinutes + recipe.cookTimeMinutes) throw new Error(`Invalid timing: ${recipe.recipeId}`);
    if (recipe.ingredients.length === 0 || recipe.steps.length === 0) throw new Error(`Missing ingredients or steps: ${recipe.recipeId}`);
    if (!recipe.ingredients.some((item) => item.substitutions.length > 0)) throw new Error(`Missing substitution guidance: ${recipe.recipeId}`);

    for (const item of recipe.ingredients) {
      if (!item.ingredientId || !item.name.trim() || !item.nameArabic?.trim() || item.quantity <= 0 || !item.unit.trim() || !item.group.trim()) {
        throw new Error(`Incomplete ingredient: ${recipe.recipeId}/${item.ingredientId}`);
      }
    }

    for (const step of recipe.steps) {
      if (!step.title.trim() || !step.titleArabic?.trim() || !step.instruction.trim() || !step.instructionArabic?.trim() || !step.cookingCue.trim() || !step.cookingCueArabic?.trim() || !step.heatLevel?.trim() || !step.heatLevelArabic?.trim()) {
        throw new Error(`Incomplete cooking step: ${recipe.recipeId}/${step.stepNumber}`);
      }
    }
  }
}

assertRecipeQuality(recipeExpansionSeed);
